### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by hairydogltd** [cubecart/v6#101]
I'm sorry, this is possibly not a bug, but an info request 

I am working on a new skin, but not based on the over-complex Foundation template (which I detest). I've based it on Kurouto skin, then stripped some of the div-itis from that.

Unfortunately, I've not been able to make the star selection work in Write a Review - and now I see that it doesn't work in Kurouto skin either.

Can you give a clue about what has changed that might have killed the star selecting functionality, apart from hiving it off to an element file?

**Comment by bhsmither** [comment]
If you take this to the forums, you and I can explore what may be going on.

**Comment by abrookbanks** [comment]
> I am working on a new skin, but not based on the over-complex Foundation template (which I detest).

There are some *really* important points I need to raise around this comment.

* It may appear over complex if you are not used to working with responsive frameworks but it is a *crucial* skill to learn. http://foundation.zurb.com/docs/
* If your store is not responsive it will cost you sales as customers on unsupported devices will leave. There are a whole bunch of stats about to support this statement. 
* Agreed it doesn't look great but this is intentional as it a blue print if you like with minimal styles. It has been designed for exactly what you are trying to do. Once you get it you'll find development is actually faster.

Thanks for raising the issue about the stars. I expect this has stopped working since the version of jQuery has been updated. I'll take a look asap.

**Comment by hairydogltd** [comment]
Thanks for looking at that, but not only do I dislike the ludicrously over-complexity of the Foundation skin's approach (there are much better ways to make a flexible layout) and by the look of it (second-rate WordPress) but I'm unconvinced by responsive websites that present a different UI to mobile devices, On my smartphone, the first thing I do when visiting a website is to turn the phone landscape. The second thing I do is "request desktop site". 

You can assert that non-responsive sites lose sales, and it may be true for some sites. My experience is the opposite. Responsive sites generate more customer questions but not more sales.

**Comment by abrookbanks** [comment]
I locked this as maybe its better to have such a debate on the forums. Ideally GitHub needs to stick to bugs. I'd be careful to impose what you do (and assume is best) on your customers.

**Comment by abrookbanks** [comment]
Relates to issue #102
