### ISSUE TITLE
Disable auto detect of cache utility

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1036]
Too many hosting companies have memcache installed but not allowed for "basic" hosting account. 

For this reason CubeCart should default to file cache unless otherwise specified in the includes/global.inc.php file.

**Comment by abrookbanks** [comment]
Fixed with 2d6a0802698a55f5f803a318c7539eb6b0b66d3a

**Comment by havenswift-hosting** [comment]
If this is going to be changed, then on an upgrade to 6.0.11, if there is no entry in global.inc.php (i.e. currently using Memcached), then you need to add an entry for this otherwise all sites upgrading are going to drop back to using the (far) inferior files based caching.  Unlike other lesser hosting companies, we provide Memcached for ALL hosting customers by default
