### ISSUE TITLE
UK Counties no longer used by Royal Mail

### ISSUE THREAD

**Issue by PeteW1959** [cubecart/v6#1071]
The Royal Mail no longer use counties in addresses, and the list of counties in CC is horribly out of date. (e.g. Humberside hasn't existed since 1996; it was replaced by North Lincolnshire, North East Lincolnshire, Humber, Hull & East Riding, none of which appear in the list).

All 'County' boxes within CC are 'required' fields; these should now be optional at the very least, or even removed completely.

**Comment by keat63** [comment]
You can clear the zones in the database table, this will allow the county field to be free text.
Alternatively, I have an updated list of UK counties if you want to PM me on the forum.

**Comment by PeteW1959** [comment]
Thanks, will give clearing the zones a go.

**Comment by havenswift-hosting** [comment]
Updating the counties is a better way to deal with this problem and this really needs doing at a core level so they are correct for everyone instead of being very out of date and having entries that are not counties as pointed out.  However, I would also support the removal of this field for UK addresses as the Post Office actively discourages people from using counties in UK addresses
