### ISSUE TITLE
Changes to product option pricing functionality

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1097]
1) A product should either use absolute product option pricing or not - I dont think it should be selectable on an option by option basis as doesnt make sense to have it on one option and not on another.

2) If absolute option prices are being used, then options should also be forced to be required - it doesnt make any sense to charge different absolute prices and allow customers to add products without selecting an option

3) If absolute option prices are being used, then the display price should show "From X" where X is the lowest option price set for that product

4) Currently absolute pricing doesnt seem to be working correctly - if a base price is set (say £5) and absolute option prices are also set and you select one for £10 and then add that to the basket, the price added is £15 as if not using absolute pricing

**Comment by briansandall** [comment]
There are cases where a product may have absolute pricing options mixed with non-absolute pricing options. Example: a t-shirt where the size option uses absolutes, but you for +$5.00 you can add a custom name tag.

If point 1 was implemented as you suggest, that type of product / combination of options would no longer be possible.

Similarly, I don't see why an option with an absolute price should be forced to be required; while cases may be few and far between where that's not the case, the framework should certainly allow it. 

I'd prefer as few restrictions as possible - CubeCart enables store owners to set up their products however they like, rather than limiting them.

Point 3 would be great to have.

Point 4 is related to #902

**Comment by abrookbanks** [comment]
I've put this as a feature request as I want to overhaul this a bit. Having a "from" price would be great. I'm keen to implement that based on lowest absolute option price or lowest quantity discount.

Essentially if a product has variance in price "From £x.xx" is essential.
