### ISSUE TITLE
Feature Request: Multi-domain support

### ISSUE THREAD

**Issue by Spechal** [cubecart/v6#1213]
It would be nice to be able to use multiple domains for a single installation so the product catalog can be shared among them and selected for which domains to display.  In example, I have coin related domains and a main company domain.  It would be nice to have all products show on the main domain and only other products that are relevant to the other domain appear.

**Comment by Noodleyman** [comment]
I've some solutions for these kind of setup's, but it really depends on what you are looking for. I've written an API for CubeCart which allows the push/pull of data from a central store to other stores. It keeps in sync your inventory/orders/prices/customers etc, but more importantly it allows you to manage all of your additional stores from a single parent store.

Within the parent store you can configure via the admin area which products are sent to which sites. 

I would rather use this method because you can essentially have multiple CC installs, configure then differently, brand them differently and manage them all as one.  want to disable a product on one of the child stores? simply uncheck a box on the parent store and it will take care of it for you. 

My solution is in use on a few stores out in the wild, but is bespoke based on each customers requirements.

**Comment by Spechal** [comment]
I would see it more like a Drupal multi site install with a selectively shared catalog. However, making modules to handle secure push/pull would work too.

-Travis
