### ISSUE TITLE
W3C Compliant ISSUES

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1214]
This is the output of W3C compliance of the demo store product listing:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fdemo.cubecart.com%2Fcc6%2F3d-glasses-tdg-br200%2Fw.html

**Comment by havenswift-hosting** [comment]
It would be good to get these issues sorted out on all major pages in the standard Foundation skin

**Comment by briansandall** [comment]
The duplicate ID errors are caused by the off-screen elements that dynamically display based on window size, such as the 'mobile' category menu, search bar, and alternate basket. I think the IDs are identical because that's what is used for JS validation, among other things, and that was an easy way to have the same logic occur for both versions of each of those elements.

Updating to be fully W3C compliant will be a major change with lots of potential for unintended (but fixable) consequences. To maintain stability of current stores, I think this would be best done at the next major version change.

**Comment by abrookbanks** [comment]
This is closed but needs to be an ongoing part of development.
![screen shot 2016-09-01 at 10 27 13](https://cloud.githubusercontent.com/assets/4520803/18162566/d48892de-702e-11e6-8e6d-ac2b1ce24258.png)
