### ISSUE TITLE
Top-Bar Dropdown Issue

### ISSUE THREAD

**Issue by dieseld23** [cubecart/v6#122]
When clicking on a item on the top-bar that has sub-menu items, rather than just locking the menu open, it expands the entire section.. See pictures for better idea what I mean.. 

![capture](https://cloud.githubusercontent.com/assets/5695864/5889517/a29cbb7c-a3f9-11e4-9a6e-27d14d1841da.PNG)

**Comment by abrookbanks** [comment]
Hmm what's the specific browser version you are using?

**Comment by dmaslach** [comment]
Firefox 35, but same thing happens in IE11. Happens when I hover over TV & Home Cinema and click it. When you move the mouse off the button, the dropdown goes away but the expanded menu you see in the picture stays. 
I also have the same problem in another dropdown without cubecart, so may be a Foundation issue?
I've tried clearing all cubecart/browser caches in case but no change..

**Comment by dmaslach** [comment]
I found this solution in the foundation forums..
http://foundation.zurb.com/forum/posts/1581-topbar-dropdown-height-issue  (with updated row number to reflect version used in cubecart)

In foundation.topbar.js:

Change row 227 from:
topbar.css('height', $this.siblings('ul').outerHeight(true) + topbar.data('height'));

to:
if (!self.small()) {
    topbar.css('height', $this.siblings('ul').outerHeight(true) + topbar.data('height'));
 }

Fixes the problem for me..

**Comment by abrookbanks** [comment]
Thanks for this!
