### ISSUE TITLE
Feature Request. Exclude items on sale from global sale mode

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1222]
If an item has a sale price configured (sales mode per product) and then the site is put in to "Global Sales mode" the retail price is used as the benchmark to calculate the discount.
In certain circumstances, this can increase the price of said item.
eg 
Retail Price £20, 
Sale Price £16. 
Global sale price @10% = £18
A checkbox to exclude items already on sale from a "Global Sale" would be ideal.

**Comment by Noodleyman** [comment]
Although I like the conept of this, it does sound like a data management issue. Global sales mode is intended to discount all of your retail prices by X amount, as per your example that is what it is doing.

Per item sale mode gives you item by item control over the sale prices, allowing you to define a set discount price for each item. Essentially what you are looking for is a "mixed" mode, or a new sale mode. "Global discount items not already on sale".

You may be able to use this module to help manage your sale prices:
https://www.cubecart.com/extensions/plugins/bulk-update-sale-prices-by-category

**Comment by keat63** [comment]
The issue from my side is that we have a number of discontinued items which we are selling off at cost price (currently we have 71 different items), each of which are all individually marked.

About 4 times per year, we offer a global discount (usually 10 or 15%).

To exclude the 71 sale items from a 'global sale', would involve changing their retail prices or marking them all as unavailable.

The last thing we really want to start doing, is changing individual prices before and after a global sale, as this would an inefficient waste of resources.

I guess which ever way we put it, a 'mixed mode' or 'exclude items already on sale mode' would work

**Comment by Noodleyman** [comment]
If you need this feature sooner rather than later, let me know. I can certainly put it together for you as your looking for.

**Comment by jasehead** [comment]
We had the same issue recently - some end-of-line items marked down to clear and then a storewide discount sale.  Had one customer buy an item at $18 instead of $2 before we realised - had to partially refund the customer, then go through and manually change the prices so they sold for $2 after storewide discount, then change clearance prices again after the sale had ended.

+1 from me that the storewide discount should have a checkbox not to discount already reduced items - in the case where a storewide discount would actually increase the price. Basically, cubecart should test for whether the manual discount or the global discount is less and apply the lowest price for that item.
