### ISSUE TITLE
Smarty Email Contents Test Parser

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1229]
It would be cool to have a button to test all email contents for Smarty parse errors. Or a test on save that it parses successfully.

**Comment by Noodleyman** [comment]
I am intreeged how this is going to work. The main issue with editing templates that contain smarty / special characters using FCKEditor is that it will translate the characters into character codes.

It does this when the editor loads the content from the database, rather than on save. So, you can have a well formed content in the DB, and simply the act of loading it into the editor changes the code. When it's saved it writes back the malformed code and breaks the parsing of it. Unless you as the editor manually modify the content source every time and swap out those characters it's not going to resolve the main issue.

It will be handy to "test" for these problems, but it doesn't really address the underlying problem which is more critical. It's tripped me up so many times, and lost me some sales of some of my modules which use the template system I've dropped it from my more recent modules and reverted back to using template files instead.

Is there a way that FCKEditor can be modified to prevent it from using HTML entities on smarty code?

**Comment by abrookbanks** [comment]
CKEditor shouldn't malform smarty tags in recent releases. It certainly used to but I am sure it can in some cases still. 

Any curly brace wrapped variable will be ignored and foreach tags are no longer messed with but we had to write a work around to put them in HTML comments so they weren't forced out say for example a table row tag. 

It's quite stable now. There are potentially other smarty tags that will cause problems such as "for", "while" and "section".
