### ISSUE TITLE
Padding (gap) required on Foundation category view (when image is present)

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#137]
When a category has an image associated there is no gap to the sort drop-down (as below).  Page  is fine when its text only.

![category view with image requires padding](https://cloud.githubusercontent.com/assets/10531097/5926153/da60f294-a660-11e4-88b1-a1cc488f0545.png)

**Comment by hairydogltd** [comment]
I'd also point out the lack of a gap between Material: Solid Oak and Finish: Painted inlay at the bottom of your screen capture.

**Comment by NaturalSigns** [comment]
Thanks but the "Material: Solid Oak and Finish: Painted inlay" text is a true reflection of the current product listing.  I imported my catelogue from a .csv file and not formatted any of the listings yet untill I am happy that the new cubecart.

**Comment by abrookbanks** [comment]
This was fixed by using one of the CSS helpers ".marg-bottom" from the cubecart.helpers.css file.
# Before
![before](https://cloud.githubusercontent.com/assets/4520803/5934565/08ff5e5c-a6c9-11e4-8958-c8614bbbf4f0.png)
# After
![after](https://cloud.githubusercontent.com/assets/4520803/5934568/0bda1342-a6c9-11e4-8567-4d2b7e2d16b3.png)
