### ISSUE TITLE
AJAX Price Format Response to be Associative

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1459]
Request that `CubeCart->loadPage()`, `_g=ajax_price_format`, be coded to observe array keys.

Suggest:
```
foreach($_GET['price'] as $key => $price) {
  if(is_numeric($price)) {
    $prices[$key] = $GLOBALS['tax']->priceFormat($price);
  }
}
```
This allows the skin designer to use 'ptp', 'fbp', and any other price indication that plugins may add, such as 'pwt' (price_with_tax), and allows for dynamic price updating across all prices. (The skin designer will need to customize 2.cubecart.js, price_inc_options() and specification_inc_options(), of course.)

**Comment by briansandall** [comment]
To clarify, `specification_inc_options()` is not part of the standard CubeCart code - that method is from my own customized site and doesn't use `ajax_price_format` for its processing but rather another custom section of code.

I left the original .js and processing code in because at one point I had broached the subject of perhaps integrating some or all of these changes into CubeCart, but it never went anywhere.

Not that any of the above invalidates this request, but I wanted to clear up any potential misunderstanding.
