### ISSUE TITLE
Options out of stock messy

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#1485]
The only way to mark a product option out of stock is to use the options matrix.
The options matrix is messy and cumbersome, it also generates it's own part numbers, which could cause confusion.

A simplified method to mark a product option out of stock would be desirable.
A simple check box would suffice.

**Comment by briansandall** [comment]
If you are tracking stock separately for different options, each of those distinct versions should have its own SKU / product code, either via the options matrix or as its own product entry.

Can you give an example of a product option that needs to track stock but shouldn't have its own SKU / product code?

**Comment by keat63** [comment]
Hi Brian

Its very difficult to explain in text.

Our stock is generally infinitum, replenished frequently and fast moving, for this reason we rarely use the stock level part of the cart.

We sell electrical terminals, which come with a 6, 8, 10, 12, 14 or 16mm hole, We also sell them in packs of 10, 50 or 100.  
https://www.beal.org.uk/electrical-products/copper-tube-terminals/copper-tube-terminals-50mm%C2%B2-cable-size.html.

These are listed as 1 single product, with multiple options.

If say the one with the 6mm hole goes out of stock, I'd have to create an options matrix.
The options maxtrix thus creates 18 entries for the different permutations. 
To the untrained none technical eye it causes confusion.

I propose something simpler, just a simple check box at the side of the product option.

I produced a mock up on the forum last week if it helps.

https://forums.cubecart.com/topic/52119-simplified-out-of-stock-options/

**Comment by briansandall** [comment]
I understand your situation exactly - we have many such products on our own store.

In the particular case you described above, you only need to include the 'Stud Size' options in the product matrix, so there will only be 6 entries. The pack quantity can remain as a separate option, and the stud size stock levels can be tracked.

That said, we have some products with over 200 option matrix entries as a result of multiple required options, and yes, it is intense. Luckily for me, we don't need to track stock levels - I use the matrix so that the selected product options display the proper product code and shipping dimensions. It would probably be easier and certainly better for search engines if I broke these up into separate products, but my brain thinks in options...

Anyway, I like the mock-up you made, it looks nice and easy to use. I imagine an additional column in `CubeCart_option_assign` in combination with a skin edit and a little extra logic when processing server side would suffice. It shouldn't be too difficult, but I'm currently busy on other projects and won't be able to fiddle with this for some time.

**Comment by keat63** [comment]
We discussed that should you guys take this up, it could be a few months in the making.
I've employed the services of SemperFi to see what Daren can come up with.

Maybe something for a future version.
