### ISSUE TITLE
Admin Folder/File rename with every upgrade

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1503]
As above for some users. Please investigate.

**Comment by Dirty-Butter** [comment]
USING TODAY'S COMMIT approximately 6:40PM Central Time USA - I just tried the Upgrade tab on dirtybutterestates.com. The code was already on today's commit, but I haven't upgraded via admin since 6.1, so History still showed me at 6.1. I first did my usual - uploading the setup folder and then running. It installed to 6.1.4, but not to 6.1.5. The ini.inc.php showed I was on 6.1.4. a few tables showed as duplicates that were not duplicated previously. My renamed admin folder/file were intact. Login url was as it has been.

Then I tried the upgrade via admin, hoping to get it to show the upgrade to 6.1.5. The upgrade was successful, but I got the warning to bookmark my newly named admin. (I already had one - now a new name). My named admin folder was also renamed. Includes.inc.php now has the NEW names for folder/file - NOT mine).

Is there anything I can send you that would be of any help? Or maybe Ian can get some server log info for you?

**Comment by abrookbanks** [comment]
Your upgrade won't be using this code as it gets overwritten with the code from 6.1.5. it will only work from 6.1.6 to 6.1.7.

**Comment by abrookbanks** [comment]
I think I was wrong with my previous comment and thanks for testing. This issue is still open so there are more tests to do still.

**Comment by abrookbanks** [comment]
I think the big problem here is that in most cases the web server can't rename the admin folder. 

A different approach is needed..

**Comment by Dirty-Butter** [comment]
I'll overwrite the estates install with my backup this morning, unless there's anything of any use to you as it is now. That's the first time I've run the install routine from within CC in a very long time.

**Comment by abrookbanks** [comment]
This new solution seems to be working really well. It's a pig to test as new install needs to be done each time etc...

More testing before I close. Sadly it won't work for merchants until they upgrade from 6.1.6 to 6.x.x.

**Comment by abrookbanks** [comment]
This is working great! Closing. 

Upgrade to 6.1.6 is going to have the same problem still as the code in 6.1.5. 

Either a manual upgrade will have to be done or this file needs to be replaced prior to upgrade. 
https://github.com/cubecart/v6/blob/master/admin/sources/maintenance.index.inc.php

**Comment by Dirty-Butter** [comment]
Will this new approach require that the store's previously renamed admin file/folder names include the word admin in them? Or will any previous naming work, like chocolate for the admin_xxx folder and vanilla.php for the admin_XXX php file?

**Comment by abrookbanks** [comment]
Any name will be fine. :)
