### ISSUE TITLE
Email validation de-focuses input after each key press

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#1589]
After failing to validate the first time, for example by trying to submit an empty registration form, it becomes very difficult to type an email address into the input field because after every key stroke following the `@` symbol, the input turns grey for a second and the input loses focus, forcing the user to click on the input again to be able to enter in the next character.

Note that this continues to occur even if the form is reset via the button, but not if the page is reloaded.

**Comment by briansandall** [comment]
Hm, on my local fork, the input gets refocused automatically after each key stroke, but it is unreliable if you are a fast typist; i.e. some key strokes may not register.

Hitting `backspace` occasionally ends up causing the browser to go back to the previous page.

**Comment by abrookbanks** [comment]
There's no choice. It will only do this after it has been validated as a legit email address. After this time it looks up if the address is in use or not. It can't be active before the result has been passed back because the session token for CSRF will be invalid and all hell will break loose. 

So this will only happen if the customer typed their email address wrong or if it is already in use.
