### ISSUE TITLE
CSRF Warnings hurting sales

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#1646]
I have two password protected test sites on latest commit, plus plushcatalog on master on the same domain. I sometimes work from my laptop and at times from my Kindle. Both are on the same network and IP address. I am the only one working on Admin.

I'm erratically seeing CSRF warnings on the front end of the stores for no apparent reason. They persist even after a hard refresh. Our sales are lower than expected in May. I can't help but wonder if our customers on plushcatalog are seeing these warnings and fleeing.

**Comment by abrookbanks** [comment]
I would suggest turning CSRF off. 

https://github.com/cubecart/v6/blob/master/skins/foundation/config.xml#L20

Set to "false". Then use the foundation JavaScript from an older version.

**Comment by Dirty-Butter** [comment]
Thanks! I changed to 6.1.5 js folder in the Foundation based skin. Is that JavaScript OK to accomplish this?

**Comment by abrookbanks** [comment]
Yes I think that's a good plan so long as csrf is set to false.

**Comment by abrookbanks** [comment]
Thanks. :P

**Comment by briansandall** [comment]
That may work for now, but how do you plan to handle this as newer versions are released that may not work perfectly with earlier JS? Not to mention such stores will miss out on any improvements and security fixes to the CubeCart JS file.

Also, if disabling CSRF is the recommended solution for actual real stores, then in practice, CubeCart stores will be vulnerable to whatever security holes were pointed out that triggered the addition of the CSRF functionality to begin with.

Sorry, but I can't accept that this is the 'solution.'

**Comment by Dirty-Butter** [comment]
I thought that, too. Hopefully this will be temporary while I look for possible causes. I'm thinking it's a wordpress blog in a subdomain of the store domain. That re-direct from movementdisorder.dirtybutter.com to dirtybutter.com/movementdisorder/ is part of the trouble - maybe all of it.

**Comment by Dirty-Butter** [comment]
Is there not some way to safeguard the store, but not show the warnings on the customer side? Maybe log the storefront csrf incidences in admin?

**Comment by briansandall** [comment]
> Is there not some way to safeguard the store, but not show the warnings on the customer side?

Sure, but the warning should only ever come up when an action was prevented, like when trying to log in or check out, so instead of seeing an error message, the customer will just be left on the redirect page with no idea why their action failed.

However, since it sounds like this issue is being caused by a redirect external to CubeCart, I'm not so worried about it anymore - in fact, assuming that your redirect involves some sort of action on the page (such as logging in), this is exactly the kind of situation that the [CSRF](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)) token is designed to prevent.

Perhaps we can get the ability to whitelist requests from certain sites? However, that could potentially open you up to CSRF attacks via IP spoofing.

**Comment by Dirty-Butter** [comment]
I'm totally out of my depth on all this - I just need the security without scaring customers away. Hopefully the blog move will solve most of it, if not all.

**Comment by Dirty-Butter** [comment]
I'm satisfied that my issues are related to CSRF tightening on the Wordpress site at the domain level, while my store is on a subdomain. The two CSRF solutions appear to be fighting each other.

https://forums.cubecart.com/topic/52610-cant-print-order-packing-slip/?do=getNewComment
