### ISSUE TITLE
Category breadcrumb not honouring custom SEO url path

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#1648]
This happens under the following conditions

1) "Add category to product URL path?" and "Add subcategories to category URL path?" both set to NO

2) Top level category "ABC" has a sub-category "XYZ"

3) Sub-category XYZ has a custom SEO url path in the form "category/sub-category-name"

When going to the ABC category page, the sub-category links for the image and the sub-category name are correct.

However, if you click to go into the sub-category, the category breadcrumb link does not use the custom SEO url and if clicked on, gives a 404 error

**Comment by bhsmither** [comment]
The quick and dirty solution is to not use slashes in the custom SEO Path.

The problem is that `SEO->SEOable()` re-generates a path if given a `_a`-style URL. This regeneration may not be the same as the existing path.

In SEO->generatePath(), if `Config['seo_cat_add_cats']` is off, then everything but the part after the last slash is dumped.

Suggest using `$existing path` verbatim.
Assuming `$existing path` does not exist, suggest moving the `seo_cat_add_cat` code to immediately after `SEO->getDirectory()`, then `setdbPath()` the result.

**Comment by abrookbanks** [comment]
Thanks for this! :)
