### ISSUE TITLE
Can't use method return value in write context [file] => classes/session.class.php [line] => 634

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#1716]
As above.... this blocks CubeCart working on PHP 5.4 only.

**Comment by Noodleyman** [comment]
this is one of those PHP 5.4 things that keeps tripping me up as well ;)

I think I'm going to drop support for anything other than PHP5.6 and higher for my modules soon. There is no reason to be on anything lower than this.

**Comment by havenswift-hosting** [comment]
>>I think I'm going to drop support for anything other than PHP5.6 and higher for my modules soon. There is no reason to be on anything lower than this.

Agreed !  With EA4 in cPanel, it makes switching PHP versions extremely easy and there is no excuse any longer.  We actually remove the option of switching to 5.4 or 5.5 on our servers

**Comment by abrookbanks** [comment]
Agreed but from my experience I'd say there are significant implications. Don't forget that CubeCart v6 came from v5 which was developed around early versions of PHP 5. On those grounds, right now it takes little of the advantages of the newer PHP versions anyway. 

There is no doubt that restricting older versions is a bad decision commercially. You could be cutting your nose off despite your face. I saw a cliff edge drop in new stores month on month when we dropped PHP 5.2 support. Coincidence? Maybe.. 

I still see older CubeCart stores wanting upgrades on servers running PHP 5.2. Some of these clients on are cPanel servers that haven't been updated to have multiple PHP version support (Lunar *cough* Pages). They then have a good 24 hours downtime as they are moved to a new server. I've seen this once this week already but its common place. 

Maybe CubeCart version 7 should be written from the ground up from PHP 7.1 but then you will enter the territory of upgradability especially where custom skins are concerned and having exact same functionality and more. I have experience this with the release of v5. 

All in all software development, backward compatibility and upgradeability is all very complex. Trading off between keeping existing customers happy and exciting new ones with cutting edge tech is no small task.

**Comment by abrookbanks** [comment]
> We actually remove the option of switching to 5.4 or 5.5 on our servers.

Thats impressive that you can do that. Don't you come across uses having really old scripts running requiring horrendous settings like register globals (*shudder*) to be on?

**Comment by abrookbanks** [comment]
[I've seen so many companies alienate customers](http://forums.kayako.com/threads/offer-a-self-hosted-solution.45219/)

Remember the new version of ModernBill?

**Comment by havenswift-hosting** [comment]
EA4 (with the multi-php selector with choices from 5.4 and above) has been mandatory since WHM 62 (three major versions ago) so hosting companies not offering this are not only not upgrading WHM/cPanel, they wont be upgrading PHP and even the server kernel.

We have a few clients with highly customised V4 sites and even a couple of V3 sites (and a few running different old CMS systems) - these are either on dedicated servers (if big enough) or we have them on one server running Cloudlinux which at least ensures secure versions of older PHP versions but that server is running latest WHM and kernels.  ANY hosting company that doesnt follow something similar is in my opinion extremely irresponsible not just to their customers (but the big boys dont care about their customers anyway) but to the internet in general.  It is also extremely short sighted of them at 5.2 is approx 100% slower than PHP 7.1 - so they could cram 2000 sites on each overloaded server instead of cramming 1000 now :)

It is more difficult for popular software developers but at some stage even they have to bite the bullet (PHP 7.2 RC1 has recently been released) and even WordPress with their massive installed base is considering forcibly upgrading sites

**Comment by abrookbanks** [comment]
> ANY hosting company that doesnt follow something similar is in my opinion extremely irresponsible

Totally agree.

> so they could cram 2000 sites on each overloaded server instead of cramming 1000 now 

LOL

> at some stage even they have to bite the bullet (PHP 7.2 RC1 has recently been released)

Agreed. CC needs to plan for this.

**Comment by bhsmither** [comment]
> "Maybe CubeCart version 7 should be written from the ground up from PHP 7.1"
What would be on the roadmap (the _real_ roadmap or pie-in-the-sky wishes) that can only be solved by PHP7?

**Comment by abrookbanks** [comment]
@bhsmither I take your point. In an ideal world I'd like the code architecture of CubeCart to be totally different.
