### ISSUE TITLE
Unused and Missing Hooks

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1757]
In hooks.xml:
In list but not found in any code:
```
admin.category.pre_smarty
admin.order.index.post_display
class.cubecart.display_content
class.cubecart.display_checkout_gateways
class.cubecart.display_basket.related
class.user.get_session_data
class.ssl.pages
```

Found in code but not in list:
```
CubeCart_6.1.10\admin\sources\orders.index.inc.php
(768): foreach ($GLOBALS['hooks']->load('admin.order.index.list') as $hook) include $hook;
----------------------------------------
\CubeCart_6.1.10\classes\cart.class.php
(851): foreach ($GLOBALS['hooks']->load('class.cart.get.fetchtaxes') as $hook) include $hook;
----------------------------------------
CubeCart_6.1.10\classes\cubecart.class.php
(1256): foreach ($GLOBALS['hooks']->load('class.cubecart.construct.complete') as $hook) include $hook;
----------------------------------------
CubeCart_6.1.10\controllers\controller.admin.session.true.inc.php
(87): foreach ($GLOBALS['hooks']->load('admin.'.strtolower($_GET['name'])) as $hook) include $hook;
----------------------------------------
```

**Comment by abrookbanks** [comment]
Thanks Brian.

**Comment by abrookbanks** [comment]
Turns out many of these were used by 3rd party extensions. Oversight by both of us I think. 

They need to be put back into 6.1.13.

**Comment by SemperFiWS** [comment]
This one:
```
----------------------------------------
CubeCart_6.1.10\controllers\controller.admin.session.true.inc.php
(87): foreach ($GLOBALS['hooks']->load('admin.'.strtolower($_GET['name'])) as $hook) include $hook;
----------------------------------------
```
is what is responsible for loading a new page in admin introduced by a plugin.
e.g.
- ?_g=plugin&name=email_customer
- ?_g=plugin&name=manage_order_refunds
- ?_g=plugin&name=manage_global_product_tabs
- ?_g=plugin&name=manage_deluxe_related_products
- ?_g=plugin&name=manage_site_news
etc

It has existed in various forms since 5.0.0 was released.
i.e.
5.0.0
![image](https://user-images.githubusercontent.com/6945093/31677559-2781a7de-b339-11e7-87bd-75b0b1dc89e4.png)
5.2.17
![image](https://user-images.githubusercontent.com/6945093/31677572-33b412e4-b339-11e7-8a71-720eae0ad4b3.png)
6.0.0
![image](https://user-images.githubusercontent.com/6945093/31677580-3ccf3d40-b339-11e7-85eb-5f1c843ff7de.png)
6.1.11
![image](https://user-images.githubusercontent.com/6945093/31677595-4898969e-b339-11e7-95a1-6a76705ec55e.png)

Without it, the new URL will load, but without tab(s), breadcrumb and page content.
So getting that restored ASAP is very important.

Whilst none of these:
```
<hook trigger="admin.order.index.post_display" deprecated="" /> (was replaced)
<hook trigger="class.cubecart.display_checkout_gateways" deprecated="" /> (removed)
<hook trigger="class.cubecart.display_basket.related" deprecated="" /> (removed)
<hook trigger="class.user.get_session_data" deprecated="" /> (removed)
<hook trigger="class.ssl.pages" deprecated="true" /> (removed)
```
appear in my plugins, they should probably also be restored in case they are being used by other 3rd party plugins or official CubeCart extensions.

Also as an FYI, if you go here:
https://github.com/cubecart/v6/issues?utf8=%E2%9C%93&q=hook%20request
you will see all the hooks that have been requested and implemented at some point.

**Comment by abrookbanks** [comment]
I'll patch this tomorrow and anyone with problems can use the code from the 6.1.13 branch.

**Comment by abrookbanks** [comment]
It's annoying because normally I'd put this into a developer preview a week before release but with this monster security issue it got rolled out quickly.

**Comment by bhsmither** [comment]
These hooks that are listed but not in any (core) code. A new developer would think they would have to be somewhere - until educated otherwise,

Perhaps eventually plugins can be better uncoupled from CubeCart core code. That is to say, there should be no core code dedicated to support specifically any particular module.

So, that opens a can of worms (re: Per Category, etc), but my assertion is that a plugin needs to manage everything about itself by itself.

**Comment by abrookbanks** [comment]
See: https://github.com/cubecart/v6/commit/0364d64c56538a7b81a23dec247d052fdf0eeae6#commitcomment-25204449
