### ISSUE TITLE
6.1.11 - Unable to visit store as logged in Admin when offline

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#1759]
With the upgrade, did a new install also to confirm issue.  When store is offline, a Logged in Administrator is unable to visit store and are taken to offline page.

**Comment by sumwonlost** [comment]
Also when logged in user (customer) change skin, when they logout it reverts to default skin rather than using changed skin

**Comment by havenswift-hosting** [comment]
I can confirm the first point with not being able to access offline store even when logged in as admin.

**Comment by havenswift-hosting** [comment]
It also prevents an admin logging in as a customer - was all working prior to latest upgrade and getting multiple reports since upgrading of this failing as well - CSRF issue ?

**Comment by The-Model-Tree-Shop** [comment]
We too cannot login as a customer using the login tab (see picture) from the admin panel since the upgrade, this is a real inconvenience for non PC users who need you to do their order form them on the phone.
<img width="219" alt="login" src="https://user-images.githubusercontent.com/12745472/31607163-3bfc0f32-b263-11e7-9980-ac77f2b45907.PNG">

**Comment by abrookbanks** [comment]
Fixed with https://github.com/cubecart/v6/commit/8d8b359f3032c968d9afe9f3b3f0af3bd450f11f
