### ISSUE TITLE
Edit Hook to Include Priority

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#1822]
Everything about a plugin's hooks can be (temporarily*) changed in admin, Manage Hooks, then click on the plugin's name. Then click the Edit icon of the targeted hook.

Except the priority.

Request that a plugin's hook edit screen include a text entry field to specify the priority.

* Note that only the enabled status is not reset when revisiting a plugin in Manage Hooks. if we wish to treat the priority of a hook the same, then this will also mean moving the `$record['priority']` out of the array definition and put it next to `$record['enabled']` in the `if($check)else` block.

**Comment by havenswift-hosting** [comment]
This was originally requested in https://github.com/cubecart/v6/issues/883 and is an issue especially in stores with larger numbers of modules.  Had one tonight where two plugins were conflicting due to priority order and it was solved by manually updating the priority via MySQL so it all works except that it cannot it updated via admin

**Comment by abrookbanks** [comment]
![screen shot 2018-02-22 at 14 04 39](https://user-images.githubusercontent.com/4520803/36542715-897f469e-17d9-11e8-889a-415851fa11b6.png)
![screen shot 2018-02-22 at 14 04 31](https://user-images.githubusercontent.com/4520803/36542716-89aaed1c-17d9-11e8-94d3-602bb9cc3f94.png)
