### ISSUE TITLE
Admin area - Poor Performance related to large quantity of images

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1830]
I was tasked with looking into a login performance issue, taking upwards of 2 minutes to login. The root cause of the problem was a large volume of directories and images within the /images/. directory.

Within the dashboard.index.inc.php file CubeCart scans the /images directory to calculate the overall size. 

```
$system = array(
	'cc_version' => CC_VERSION,
	'cc_build'  => null,
	'php_version' => PHP_VERSION,
	'mysql_version' => $GLOBALS['db']->serverVersion(),
	'server'  => htmlspecialchars($_SERVER['SERVER_SOFTWARE']),
	'client'  => htmlspecialchars($_SERVER['HTTP_USER_AGENT']),
	'dir_images' => dirsize(CC_ROOT_DIR.'/images', $tmp1),
	'dir_files'  => dirsize(CC_ROOT_DIR.'/files', $tmp2),
);
```

This calls a recursive dirsize function which is found in the /includes/functions.inc.php file.  However, when you have a large store with a lot of images and directories this step can take a very long time.

I think there is room for an enhancement here. Either finding a more efficient way to gather the data via PHP no demand or by scanning the directory as part of the cache building / file manager processes and storing the file sizes/totals in the database which the dashboard will just read. Perhaps a new DB table to track objects/file information outside of the /images/source directory. It will be much quicker to gather this from the DB

**Comment by briansandall** [comment]
And/or an option to disable them? While having the folder sizes in the dashboard is a nice convenience, it's not something I've ever even looked at until now. For my store, the storage space used isn't even a consideration and, if it was, it'd be something I manage via cPanel or discuss with my hosting provider.

For those of us that don't care about these stats, it'd be nice to have the page load more quickly instead.

**Comment by sumwonlost** [comment]
Can't say that I have looked at the folder sizes nor do I care, as my attitude is "what will be, will be".  If I require an image for my site, I just add it. Like briansandall, storage space is not a consideration.

My site is still in development stage, so please define a large store? I currently have over 2500 categories and each has its own image folder structure, some up to 5 levels (sub directories).  I also use BxSlider with a further 3-4 images per category, let alone images for the 1000's of products that have added in preparation for my launch in 2018..

My image directory is approaching 1Gb, I have not noticed any performance degradation with login nor anywhere else across my site with such a large volume of images, however if it improves performance, I am in agreement with the option to be able to disable this.

My issue is searching, in particular for lost files (files that have been uploaded to wrong directories) and then moving these #1792.  Yes I can do this via Plesk CP or FTP then come back and do an Update File List but I should be able to do these in CubeCart rather than do them externally.

**Comment by Noodleyman** [comment]
In the case of the store I was looking into, close to 10k folders, most with 1 or two images per directory.

**Comment by havenswift-hosting** [comment]
Optimizing this has got to be a good way forward but also agree with other comments that this information is pretty useless and think it should be option to report or not with the default to be disabled

**Comment by abrookbanks** [comment]
It could be cached or given a 2 second time out.

**Comment by abrookbanks** [comment]
Maybe the best plan is to swap it out for an ajax request on demand rather than every login. 

Image folder size: Calculate
Download folder size: Calcualte

**Comment by abrookbanks** [comment]
"Calculate" next to image folder size clicked..
![screen shot 2017-12-07 at 12 51 10](https://user-images.githubusercontent.com/4520803/33716253-56a3ed2e-db4d-11e7-98e7-8b9ebcc21c1d.png)
