### ISSUE TITLE
Unable to use more than one promotional code

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#1997]
As a customer if you try and use more than one promotional code, the most recent code is applied to the cart and the previously applied code is removed.  Ideally they should stack to allow a customer to take advantage of multiple offers if available. 

It would be helpful to have the ability to configure a promotional code to allow it to be used with other codes (stackable) or solo use only.

**Comment by hairy-dog** [comment]
There be dragons! Imagine I have a code that gives £5 off, a code that gives 10% off and a code that gives 30% off.
A customer buys a £100 product. They use all three codes. What do they pay? 
100 - 5 = 95
95 - 10% = 84.50
84.5 - 30% = 59.15
or
100 - 30% = 70
70 - 10% = 63
63 - 5 = 58.00
or several other net prices

**Comment by Noodleyman** [comment]
any percentages.. combine the % to make a single discount.. 10% and 30% combine to make 40%.

Fixed prices, interesting point. not sure if they should come first or last. My gut feeling is first. 

So apply static discounts first, reducing the 100 by X. Then apply a 40% discount on the remainder.

**Comment by hairy-dog** [comment]
In my view, any ambiguity should be resolved in favour of the customer. So that means that static discounts have to be deducted last, not first.
I'm not sure what to think about conditional discounts in multiple discounts. For example, if a discount is £5 off all orders over £100 and a percentage discount takes the order from £105 to £95, would the £5 off then be invalid? Though I've never tried to use conditional discounts in CubeCart.

**Comment by abrookbanks** [comment]
Closing as per the feature request submission guidelines.
