### ISSUE TITLE
Install on IP rather than domain issue

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2083]
After installing to an IP rather than name, you can't log into the admin area.

**Comment by bhsmither** [comment]
Your browser is probably not sending back cookies because the calculated domain in the cookie does not match the page requested (leading period).

This may be considered an "unsupported" environment - but for dev environments, there is a solution in the forums.

Personally, I would like to see a resolution in the core code to detect IPv4|6 syntax.

**Comment by abrookbanks** [comment]
CubeCart isn't really designed to operate from an IP address. You can add a domain to your hosts file to point to local hosts. This is a good solution and takes only a minute.

**Comment by Noodleyman** [comment]
It's not critical, but thought direct IP was supported based on previous conversations we've had on the topic Al which is why I reported it.
