### ISSUE TITLE
Add support for X-Frame-Options 

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2092]
Kinda associated with #2090 
See:
https://infosec.mozilla.org/guidelines/web_security#x-frame-options

https://observatory.mozilla.org/analyze/demo.cubecart.com

**Comment by Noodleyman** [comment]
To make life easier... here' some code from a site I applied it to today, seems to work OK and passed validation checks

  ######## Force strict SSL ########
  Header set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" env=HTTPS
  
  ######## X-Frame-Options to protect against nasty things ########
  Header always set X-Frame-Options SAMEORIGIN
  Header set Content-Security-Policy "frame-ancestors 'self'"
  
  ######## header tells browsers to stop automatically detecting the contents of files ########
  Header set X-Content-Type-Options nosniff

**Comment by abrookbanks** [comment]
Doesn't that block inline JS?

**Comment by Noodleyman** [comment]
not in my tests, worked fine. I set those options which passed validation checks and the store functionality was still working correctly. There may be better options to configure, that's my initial attempted based on limited research. :)

**Comment by abrookbanks** [comment]
Yes. That seems ok. I was getting confused with content-security-policy rules. I don't think we can get that tight enough to protect against XSS as we need inline JS.

**Comment by Noodleyman** [comment]
Agreed. :), I assumed some payment modules that use frames may also be impacted, so it would require some solid testing of any settings that made it into the cart, maybe even adding some config or control of the values

**Comment by abrookbanks** [comment]
I think a header of `Strict-Transport-Security:max-age=31536000;preload` is about as far as we can take this. `includeSubDomains` wouldn't be acceptable as we don't necessarily want all subdomains to have this policy. `X-Frame-Options SAMEORIGIN` is already a security feature. `Content-Security-Policy` seems to also require some server side configuration so we can't really do this.  

`Header set X-Content-Type-Options nosniff` has been added but this is dangerous because according to Mozilla "in other words, it is a way to say that the webmasters knew what they were doing" LOL

This issue and all related ones are covered now.

**Comment by abrookbanks** [comment]
The preloading bit is pretty cool I think. Especially for skins with outdated src tags to insecure URL's.

**Comment by havenswift-hosting** [comment]
See comment on https://github.com/cubecart/v6/issues/2091
