### ISSUE TITLE
Adding a scottish address does not work

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2134]
A customer from Inverness (Scotland) was about to order, but since the country "Scotland" is not listed, the customed picked "United Kingdom". However, "Scotland" was not listed under "County" (for obvious reasons), making the customer unable to order.

I have two suggestions here:

1. Add Scotland as a country

2. Disable (or atleast add an option) the enforced requirement of county usage. Where I live (Sweden) we don't even use counties in our addresses, so this option is a bit bogus.

Also, when I make an order for an overseas customer (UK for example) I usually have no idea what county the particular town is in.

Are county selection really necessary?

**Comment by bos4711** [comment]
Side note: for United States, the states are listed under "county" in Cubecart, while these are really states.

**Comment by hairy-dog** [comment]
Scotland us not a county. The Scottish counties should be listed, not Scotland On 13 Aug 2018 8:33 a.m., Rikard Bosnjakovic <notifications@github.com> wrote:A customer from Inverness (Scotland) was about to order, but since the country "Scotland" is not listed, the customed picked "United Kingdom". However, "Scotland" was not listed under "County" (for obvious reasons), making the customer unable to order.
I have two suggestions here:

Add Scotland as a country

Disable (or atleast add an option) the enforced requirement of county usage. Where I live (Sweden) we don't even use counties in our addresses, so this option is a bit bogus.

Also, when I make an order for an overseas customer (UK for example) I usually have no idea what county the particular town is in.
Are county selection really necessary?

**Comment by abrookbanks** [comment]
Surely it falls under United Kingdom with state/country set as optional.

e.g. 
44-46 Morningside Road
EDINBURGH
EH10 4BF
United Kingdom

**Comment by abrookbanks** [comment]
Please note that county/state is optional since 6.2.0 per country. Your skin may need to be updated to dynamically work around this.

**Comment by abrookbanks** [comment]
Works fine with state/county set to optional for United Kingdom. 

![screen shot 2018-08-13 at 10 18 41](https://user-images.githubusercontent.com/4520803/44023478-5aa829f4-9ee2-11e8-935f-5edbae3a1b31.png)
