### ISSUE TITLE
Promotional Codes - empty assigned products

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2153]
If you create a promotional code and configure "Product List" as "Promotional code applies to ONLY above products", and then leave the list blank, the code applies to ALL products.

This is undesirable if you are trying to create a code applicable to only shipping.

**Comment by hairy-dog** [comment]
The easy fix is to have a test product with a very low price (used for testing) and assign it to that. What happens if the only product in the list is switched off?On 22 Aug 2018 9:47 a.m., Noodleyman <notifications@github.com> wrote:If you create a promotional code and configure "Product List" as "Promotional code applies to ONLY above products", and then leave the list blank, the code applies to ALL products.
This is undesirable if you are trying to create a code applicable to only shipping.

**Comment by Noodleyman** [comment]
That is a valid work around, although not a fix.

follow up:
It's not a valid work around, as you can't use the coupon for shipping discount only until you've added the product that you've associated the code with

**Comment by abrookbanks** [comment]
Ignore the actual promo code name "freeshipping" it's actually 50% off shipping. 

![screenshot 2019-02-18 at 12 30 41](https://user-images.githubusercontent.com/4520803/52951210-15202b80-3379-11e9-8d47-8f3f9276031b.png)
![screenshot 2019-02-18 at 12 30 17](https://user-images.githubusercontent.com/4520803/52951211-15202b80-3379-11e9-89fa-1e22169c9620.png)
