### ISSUE TITLE
Out of stock product shows in sale items

### ISSUE THREAD

**Issue by keat63** [cubecart/v6#2195]
I found an item in the sale items list, which was marked as zero stock, and available for purchase unchecked.
Only removing it's sale price, did it dissapear from the sale items list.

Not sure if this is a bug, but thought it worth mentioning.

**Comment by bhsmither** [comment]
To be clear, you were completely logged out of admin?

**Comment by keat63** [comment]
Maybe not.
I'll try again tomorrow.

**Comment by keat63** [comment]
After having posted my reply, it occurred to me that it was the Boss who pointed this out to me, he wouldn't have been logged in. Anyhow, just to prove the theory, I tried again this morning and the product still shows in the sale items list if marked as zero stock and unavaiulable for purchase.
6.1.7

**Comment by bhsmither** [comment]
The following issues have been closed (fixed in versions after CC617) that relate to stock issues:
https://github.com/cubecart/v6/commit/647f12be3dc527fce9e238d7334a9c1a462e5ac1#diff-5fb297f8c51eca6a1ef7f96cd495cbcc
https://github.com/cubecart/v6/issues/2116
https://github.com/cubecart/v6/issues/2058
https://github.com/cubecart/v6/issues/1018

Thus, your observation as regards CC617 may have already been fixed.

I cannot replicate your observation on CC622.

**Comment by abrookbanks** [comment]
Please let me know if this is reproducible in 6.2.2 and I will revisit this. Thanks for the report and even more thanks for your kind patience.
