### ISSUE TITLE
Cost Price to be Recorded at Time of Sale

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2203]
Feature Request:

I am quite surprised this isn't already been requested.

I along with a lot of other people need to know the profits generated when products are sold.

A report generated that will get information stored from when a product is sold. This will show Date Sold, Item Sold, Price Sold, Cost Price and Details of who purchased it.

Other option could be available on the report.

At the moment, I can not see that the cost price is recorded at the time of the sale.

Could this be considered for a future upgrade please.

This is something that I feel is needed for a lot of people when it comes to profits and tax purposes.

**Comment by bhsmither** [comment]
The above is from Mike at:
https://forums.cubecart.com/topic/54468-new-feature-sales-report/

**Comment by hairy-dog** [comment]
Cost price would need to be stored against specific stock items. The cost price might change whilst items are in stock. Would you want the cost price to be the lowest cost price, or the newest cost price?On 29 Oct 2018 6:53 p.m., Brian Smither <notifications@github.com> wrote:Feature Request:
I am quite surprised this isn't already been requested.
I along with a lot of other people need to know the profits generated when products are sold.
A report generated that will get information stored from when a product is sold. This will show Date Sold, Item Sold, Price Sold, Cost Price and Details of who purchased it.
Other option could be available on the report.
At the moment, I can not see that the cost price is recorded at the time of the sale.
Could this be considered for a future upgrade please.
This is something that I feel is needed for a lot of people when it comes to profits and tax purposes.

**Comment by Noodleyman** [comment]
I've had this request open since 2015, would be great to see if this, and all the related items to it could finally be added. 

https://github.com/cubecart/v6/issues/619

https://github.com/cubecart/v6/issues/620

https://github.com/cubecart/v6/issues/622

**Comment by havenswift-hosting** [comment]
As hairydogltd has intimated, recording cost price isnt as simple as having one value.  What happens if you buy 10 at one price, then another 10 two weeks later at a different price but still have some of the original items in stock etc etc.  You need a way of recording cost price for a batch of stock and then a defined order (LIFO / FIFO) for reducing that stock.

While having the cost price recorded against the order would be great, if it is going to get added, it should really be properly

**Comment by bhsmither** [comment]
I would have to assume this is not a unique problem to small businesses.
How does Walmart handle this? Is it even really that much of an issue?

**Comment by Noodleyman** [comment]
it is actually quite simple. you log the cost at the time of purchase per unit and as an aggregate (in case of rounding) against the order inventory. then reports will use those numbers in their calculations.  this is a really basic thing...

**Comment by bhsmither** [comment]
The problem being batches of the same item having differing cost-basis.

I see managing this is a function square in the scope of your **accounting program** - where keeping track of each batch and their cost-basis is a core function. Exactly like your public stock investment portfolio manager where buying/selling based on that cost-basis is important for your tax (avoidance) strategy.

**Comment by Noodleyman** [comment]
the whole thing can be done in a single SQL, efficient query, it's not really a problem. some people use CubeCart as the accounting program, since it offers basic financial reports. You need the store to capture the basic information, even if you want to feed that into some other financial tracking system.
