### ISSUE TITLE
Latest Version of PHP Recommended

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2247]
Question:

Regarding #2000, can we agree that the "recommended" version will always be **the latest**?

Also, in /language/definitions.xml, for 'dashboard':
```
<string name="tech_version_php" introduced="5.0.0"><![CDATA[PHP Version (5.6 Recommended)]]></string>
```
The **latest version** being "recommended" has its many advocates and many reasons, but that have nothing to do with CubeCart's actual code requirements.

**Comment by abrookbanks** [comment]
Yes and no. It's probably best to recommend the latest version we know CubeCart is ok with. We didn't recommend 7.0 due to lack of encoders for 3rd party developers. We didn't meet 7.2 requirements until OpenSSL replaced mcrypt. 

I have changed it to 7.2 for now and I think we should continue this philosophy of hightest PHP version we are confident is ok.
