### ISSUE TITLE
After upgrade to 6.2.4. images on Product Page (Foundation) do not load well.

### ISSUE THREAD

**Issue by PedrooNL** [cubecart/v6#2257]
After I upgraded to 6.2.4 I have an issue with the images on the Product Page (Foundation) not loading well. Only after refreshing the page they come full size. 
Do others have this? 
P.

**Comment by PedrooNL** [comment]
I found out that 2.cubecart.js in the Foundation skin causes the problem. I brought back:
$('a.open-clearing img#img-preview').load(function() {
in line 4 and
      });
in line 14.
Problem solved.

**Comment by abrookbanks** [comment]
I expect this was just a browser cache issue. A hard refresh should have fixed it so long as the gallery code was updated with the upgrade.

**Comment by sumwonlost** [comment]
I have been having same issue.  It is annoying having to do a hard refresh.

I followed PedrooNL instructions and all good now.  This is temporary fix as it will be overwritten next update and have to redo.  Need a permanent solution as this is a bug

**Comment by claudia39** [comment]
I'm in the process of creating my custom skin based on Foundation from CC6.2.5.   My image was showing too small so I changed lines 4-14, I think that's right - whatever was changed in CC6.2.5, back to  the code from CC6.2.2 and it worked. However, I noticed later that my small screen would not open the left and right off canvas. No menu of shopping basket.  It took days to figure it out. When I changed back to the complete CC6.2.2 2.cubecart.js file everything worked.  Could it have something to do with the other change to that file on lines 406 and 410?  Everything else is stock CC6.2.5.  Just hope noone else had this problem. I'm going to post this on the forum too since this was closed.
Claudia
