### ISSUE TITLE
New Function + Hook request

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#226]
in cart.class.php it would be useful to have a new function.

public function customCartFunction($var1 = null, $var2 = null, $var3 = null, $var4 = null, $var5 = null) {	
foreach ($GLOBALS['hooks']->load('class.cart.customCartFunction') as $hook) include $hook;
}

This will allow devs to insert their own custom functions into cart.class.php within the hook and can control them using parameters $var.

**Comment by bhsmither** [comment]
I like this. So much, in fact, I would like to see such a thing in every class:
`public function userCall( $var = array() )`
where $var contains an array with keys specifically named for *your* hook's code.

Because the hook principle allows for no restrictions on whose plugin gets to call a hook, perhaps some sort of identifier for making sure *your* plugin's hook code for this hook doesn't cause someone else's hook code to blow up the planet when foreign and domestic arguments are passed in.

**Comment by bhsmither** [comment]
On the other hand, what is the operational considerations when a plugin EXTENDS an existing CubeCart class? I really should get more familiar with EXTENDs and INTERFACEs.

**Comment by Noodleyman** [comment]
I messed around with the extends, but ran into issues. probably due to user error though. 

My assumption was you can use the $vars statements to identify your own hook. so, perhaps make $var1 become $plugin instead. Then, in each custom hook / function just wrap it with an IF($plugin == "MyPlugin"){ } check.

I've a couple plugins that require custom functions to be added at the moment and was debugging one today which made me think about logging the request, so perhaps it can remove a step from an install guide for V6 :)

**Comment by abrookbanks** [comment]
Hmmm..... Extending HAS to be the best way surely? Any hook *should* be able to extend any class. 

Wouldn't one public function like that potentially undermine all the private functions. I'm just wondering if there are any security implications too. I'm keen to see how we can work this.

**Comment by abrookbanks** [comment]
Guys I really think that extending existing classes is the best option. For this reason I've closed this for now.

**Comment by bhsmither** [comment]
If anyone sees this, please join the conversation at:
https://forums.cubecart.com/topic/49329-overloading-classes/
