### ISSUE TITLE
Product Description bug

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#2296]
Create Product, add Product Description (leave Short Description blank) and save.

Front End - Navigate to product via Categories.  It lists all products for Category.  In expanded view, it displays the Product Description and NOT `{$product.description_short}` in product details.

If a Short Description is entered it displays the Short Description correctly else it displays Long Description.  I don't know if this is a bug or intentional?

I assume intentional as understand the logic in this as it is better to have some Description than no Description at all.

The issues.

1.  If it use Long Description, it removes the formatting, images and truncates at some point (I haven't counted) which may make the Short Description incoherent.  Admin needs to word the 1st part of Long Description carefully so it display coherently as a Short Description if not entered.

2.  If it use Short Description, it also removes the formatting, images and truncates at some point.  That being the case I ask 2 questions.

a.  Why have Short Description for product if it defaults to Long Description?

b. If you have Short Description, why use Editor if formatting is removed.  This can simply be a textbox limited to the truncated character number.  Where else is Short Description used?

**Comment by bhsmither** [comment]
Intentional, better than nothing, (as best I know) in Category listings which include Sales and Search results. This is a standard element of the product's dataset sent to the templates, therefore it can be used wherever else it is wanted.

The length is controlled by Store Settings, Layout tab, "Length of product precis".

Formatting is not removed from Short Description if the string length of the entire content, which includes HTML tags, is less than this value.

Please feel free to continue this discussion in the forums.

**Comment by sumwonlost** [comment]
Thanks for explanation.
