### ISSUE TITLE
6.2.3.sql upgrade does not have ; #EOQ on line 9

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#2354]
Currently
`ALTER TABLE `CubeCart_inventory` ADD `live_from` int(11) NOT NULL DEFAULT '0' AFTER `status`
ALTER TABLE `CubeCart_inventory` ADD INDEX (`live_from`); #EOQ`

**Comment by bhsmither** [comment]
It was removed here:
https://github.com/cubecart/v6/commit/897c1213d9a2e75894e38230911f09e8708565c0
for no apparent reason.

**Comment by Dirty-Butter** [comment]
So should the #EOQ be there? If not, how can I undo the query I ran when I added what I thought was a missing part - unless it won't hurt to leave it as-is.

**Comment by bhsmither** [comment]
The missing characters should be there.

I assume your store's are already at CC625? And for personal reasons, you are implementing changes, prior to an actual release, that you find in the Github which may eventually find their way into CC626?

**Comment by Dirty-Butter** [comment]
Several reasons - found this one bringing one of my test sites up even with the other one that was already on today's commit. I try to do the daily commit changes on the test and stock sites I have when I have time. It's easier to understand a few changes at a time, and I maybe learn a little. And MUCH easier to make decisions about whether or not any of my custom edits (mostly from you LOL) will be effected. :)

**Comment by bhsmither** [comment]
Having executed the offending statement, which also managed to include the following statement, thus making the whole thing a "syntax error" event as far as the database server is concerned, then neither of those two statements should have actually changed the database schema in any way.

So, if the store was already at CC623 or later, there should already be a column 'live_from' and an index 'live_from' in CubeCart_inventory.

If the store being changed was at CC622 or earlier, and since this statement failed, that store may still be missing that column or index.

**Comment by Dirty-Butter** [comment]
I'm OK. That was a test store I had not taken the time to keep upgraded, so it was still on 6.2.2. Since I did fix it so it would execute, I should be alright.
I will never use that feature, so my live stores probably do not have that column. Will test them all ;)

**Comment by bhsmither** [comment]
All stores at CC625 should have that column. The use of that column is hard-coded and is expected to be there.

If not, CubeCart will log an error. But won't stop CubeCart from functioning.

**Comment by abrookbanks** [comment]
Thank you.
