### ISSUE TITLE
Promotional codes not working

### ISSUE THREAD

**Issue by lamrith** [cubecart/v6#2377]
I have not changed or updated anything on my website, but suddenly now my promotional codes are not working at all.  I have a code that has been used repeatedly and unlimited usage set. Now it is not working and saying that the code does not exist.  
I have tried changing the name in case it was a syntax issue.
I have created new codes and copy/pasted the code but they still do not work.

![image](https://user-images.githubusercontent.com/23528914/64444596-5b28ac80-d089-11e9-9d43-c0ff0dd775ad.png)

**Comment by bhsmither** [comment]
None of any of your codes?

If possible, please describe one of your codes, such as the following example:
Three or four uppercase letters,
then a dash,
then four to six numbers.

There was a change in CC626 (from CC625) to the pattern used to make sure there were no funny characters in the user-submitted sequence of characters.

**Comment by lamrith** [comment]
Not a single code I have tried has worked and they are all very simple.
for example here are 3 of them.  The last one I created right before posting so it was a fresh entry in the dB in case there was some previous corruption.  
bulk200
MIL5
bulk

Here are details on my install..  I am not on 6.2.5 or 6.2.6
CubeCart Version
6.2.2
PHP Version (5.6 Recommended)
7.3.9
MySQL Version
5.7.23-23
Image folder size
24.04 MB
Download folder size
0.00 KB
Max. Upload filesize
64M
Browser user-agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
Server Software
Apache

**Comment by bhsmither** [comment]
PHP 7.3 has a new REGEX library called PCRE2. This library is very much more strict in what was otherwise somewhat lenient.

Because of PHP 7.3's PCRE2 library, **all** CubeCart installations prior to CC626 running under PHP 7.3 and later will need to implement the code changes found in issue #2308. There are two links to code changes for a total of four files edited.

It's not a case of your codes being bad. It is the case that the `preg_replace()` command is faulting under PHP 7.3.

**Comment by lamrith** [comment]
BINGO!  That fixed it.  Thanks again!
