### ISSUE TITLE
Catalogue->imagePath method doesn't handle missing images fully

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2395]

**Comment by Dirty-Butter** [comment]
I had a problem with this code change on a test site. I wanted the data to mirror my current live site, so I dropped all the tables that pertain to images, inventory, sales, and anything else that had changed since I first created the cloned site. When I copied over all those tables from the live to the test, none of the images would show - even though they are in the source folder. I double checked everything I could think of, but as soon as I commented out this new code - my images showed on the test site.

**Comment by bhsmither** [comment]
At line 1451, `$source` is referenced before it is ever set with a value. Thus, the test will always be false.

**Comment by abrookbanks** [comment]
Thank you.

**Comment by Dirty-Butter** [comment]
Glad I actually helped!
