### ISSUE TITLE
Incremental order numbers

### ISSUE THREAD

**Issue by Phrkd** [cubecart/v6#2451]
I've set a custom incremental order number (eg ABC00001) yet when payment confirmation is received the order number that is being displayed is the default CubeCart order number (eg 200115-120925-1799). Payment gateway is WorldPay using CC V6.2.8.

**Comment by bhsmither** [comment]
A possible solution for the WorldPay gateway module is:
```
In the gateway.class.php file, near line 52, find:

'MC_OID' 	=> $this->_basket['cart_order_id'],

Change to:

'MC_OID' 	=> ($GLOBALS['config']->get('config', 'oid_mode')=='i' ? $this->basket[$GLOBALS['config']->get('config', 'oid_col')] : $this->_basket['cart_order_id']),
```
I am assuming the MC_OID is a value that WorldPay uses as a Merchant Cart Order ID. As such, I also assume that we can make this value whatever we want with impunity. This is not the same as the cartId, which is what WorldPay and CubeCart agree is the primary key to identifying which order is being referenced.

The edit above says that: if the store config is set to use Incremental order numbers (oid_mode == 'i'), then use the value found in the named column used for the custom format (oid_col should hold the name of the database column 'custom_oid'). Otherwise, use the standard format found in the 'cart_order_id' column.

**Comment by Phrkd** [comment]
I have made the above amendment but it still appears that the default cubecart format is being sent to the payment gateway. 

The incremental order numbers are showing in cubecart admin, yet when going through the basket > checkout > payment sequence the default cubecart order number is still being used.

**Comment by abrookbanks** [comment]
Changing the MC_OID value could have a consequence on getting the order status to update.

**Comment by abrookbanks** [comment]
Closing this for now as it's something that may affect most gateways. I'm not sure what the best course of action is. I can't update every extension.
