### ISSUE TITLE
PayPal Pro/Express can bypass T&C

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2456]
This seems like a reasonably common issue. since the PayPal module adds a button which the customer can use to checkout, even before they register for an account... it is possible for a customer to totally bypass acceptance of terms and conditions, which for some businesses is unacceptable. 

The ability to checkout, regardless of payment method must be restricted in all cases when T&D's are required to be adhered to.

**Comment by havenswift-hosting** [comment]
We have just also had a complaint about this as it also by-passes the delivery notes / comments entry which is also crucial for some businesses.  The ability to configure the PayPal module to disable this ability is needed pretty urgently

**Comment by russellhurst** [comment]
This is very important to me and my websites as well.

Additionally the name and address information returned by PayPal is incomplete - business name and county are not shown.

For me the PayPal Checkout button should not appear in the basket, only in the checkout page.

**Comment by Dirty-Butter** [comment]
I have stayed with the Standard PP mostly because of the issues mentioned here!

**Comment by abrookbanks** [comment]
Can anyone suggest how they would next expect the user experience flow to go around this?

**Comment by havenswift-hosting** [comment]
The way the PayPal module is written allows these issues to be by-passed.

1) If T&C are required, the ability to checkout should not be allowed
2) Probably need a new setting in the plugin settings "Require entry of delivery notes / comments" and then if ticked, checkout without entry should be disallowed

**Comment by abrookbanks** [comment]
I get all that. It's more how the checkout flow is adapted to bring this into it. 

I think the easy way is to add it above the "make payment" button.

**Comment by abrookbanks** [comment]
yup.. I think I know how to approach this  :)

**Comment by russellhurst** [comment]
For me I think the Paypal Checkout button should only appear on the checkout page and not in the basket.

**Comment by abrookbanks** [comment]
> For me I think the Paypal Checkout button should only appear on the checkout page and not in the basket.

That defeats the object of express checkout and would impact conversions.

**Comment by abrookbanks** [comment]
I'm on it....

**Comment by Noodleyman** [comment]
the PayPal button shouldn't be visible / usable until T&C's are accepted (if required). Notes are optional, so not as critical 

This overlaps with: #2405

**Comment by abrookbanks** [comment]
No I disagree with that too. They need to be able to see they can checkout quickly with PayPal from the off.

**Comment by russellhurst** [comment]
So if either delivery notes or T&Cs required (new option in settings) then could the Paypal button just take them to the checkout page with possibly a message why?

**Comment by russellhurst** [comment]
if not required then straight through to PayPal

**Comment by abrookbanks** [comment]
I have a good solution.. 

1. Put the check box above "Make Payment" button. The delivery notes box can still be used.

![1](https://user-images.githubusercontent.com/4520803/74655166-d12a5700-5183-11ea-9f8c-0f8295c071e3.png)

2. Once checked the order is paid for and delivery notes stored against the order. 

![2](https://user-images.githubusercontent.com/4520803/74655197-e1423680-5183-11ea-901f-c34165a50c85.png)

**Comment by russellhurst** [comment]
How will it function for a new unregistered user? I'm also keen to get accurate billing & delivery names and addresses if they are directed straight through to PayPal from the basket.

**Comment by abrookbanks** [comment]
See the attached screenshots. After they login to PayPal from the basket they get to the screen with "Make Payment". They are then required to accept the T&C's before it will proceed. They can also enter delivery instructions.

For this to work will need to use PayPal Commerce 1.2.1 or higher with the code fix in this post. 

Contact support if you want us to do this for you.

**Comment by Noodleyman** [comment]
@abrookbanks , 

Does that mean "PayPal pro" is no more, as the fix for PayPal pro appears to be in another module?  How does todays fix work with the PayPal button which is offered to customers via the plugin on checkout pages?

**Comment by abrookbanks** [comment]
Before I answer this I need to give you a high level overview of paypal products and our integrations. Bear with me it is complex and confusing!

I'm not even sure where to start but I don't want to go into too much detail. 

The old "PayPal Commerce" extension is really "Express Checkout" and "PayPal Pro". PayPal pro has two modes, hosted (to avoid PCI issues) and card payments in a form (which has PCI liabilities). PayPal Pro has a £20/$30 monthly fee. The hosted payment integration is horrendously crap and the card form has PCI issues. Express Checkout also has a number of modes redirect, in-context and smart button to add a higher level of complexity.

Are you confused yet?  It's taken me a long time to get my head around it!

PayPal Commerce replaces this horrendous confusing old integration which is a pig to setup and encapsulates it into one package. Instead of having to seek out API details merchants can onboard by clicking a button and logging into their PayPal account. That's literally all they have to do to get setup. They then have;

- Express Checkout
- Credit Card form (similar in technology to Stripe)
- Alternate payment methods (PayPal Credit, SEPA, iDEAL, giropay, Sofort etc... )

There are no monthly fees and no PCI concerns. Merchants also get granular 3D secure control.  Their processing fees are competitive too. 

It's take me along with the lads at PayPal London about 3 months or more to build and test. Between us we are encouraging merchants to move from PayPal Standard and PayPal Checkout/Pro (not to mention PayPal powered by Braintree)!!

Anyone would think I'd got a job in the PayPal sales dept. LOL. But it is a really fab integration. 

To answer your question. The PayPal Express button isn't even supposed to show on the checkout page. The integration team at PayPal only want us to show it on the basket page (and soon product page too hopefully). This means they won't have come across the checkbox to agree to terms and conditions at all by then. It will always need to show above the "Make Payment" button. 

The flow in PayPal Commerce is better than the old extension. If the merchants customer hits the yellow PayPal after registering through the the native checkout they don't go back to the checkout page with the "Make Payment" button. Instead they finalise the payment in the PayPal modal window and hit "Pay Now" at the end. 

If you are confused which I have no doubt you will be LOL. The moral of the story is that I'm confident this skin fix along with PayPal Commerce is a winner. 

I need a lie down.

**Comment by Noodleyman** [comment]
so, in short... all other PayPal solutions should be considered legacy, and the PayPal Commerce module the go-to module for all things PayPal related (Or Braintree?)

**Comment by abrookbanks** [comment]
Yes. I would say that's right.

**Comment by abrookbanks** [comment]
Braintree is no longer an option for small merchants. PayPal are taking that arm of the company for larger corporations.

**Comment by russellhurst** [comment]
I've been trying to test this (v 1.2.2) but cannot get to the configuration screen.  On working through the 'connect your existing account' I get on completion a 'welcome to paypal' message then on returning to cubecart i'm back to where I started with no configuration settings available. Just the 'connect your existing account'.

**Comment by abrookbanks** [comment]
I haven't seen this behaviour before. Is your store at a recent version? I'm happy to look at it without a support contract. support@cubecart.com

**Comment by abrookbanks** [comment]
.... If you are not on a recent version it could be a cache bug. On return from PayPal refresh the page and you might find it changes

**Comment by Noodleyman** [comment]
I'm assuming that this is one of those modules which requires a FQDN accessible store? the module totally hangs my sessions on my local server when I try to access it, I'm assuming it's a network thing

**Comment by Noodleyman** [comment]
Turns out it threw an error:


 Security Warning: Illegal array key "{&quot;authCode&quot;:&quot;C21....... (quite a long key, full error not here for obvious reasons...)  was detected and was removed.
/var/www/html/cubecart/6-2-8/classes/sanitize.class.php on line 114,

Thrown from: ?_g=plugins&type=plugins&module=paypal_commerce

**Comment by abrookbanks** [comment]
> I'm assuming that this is one of those modules which requires a FQDN accessible store?

Yes. PayPal needs to send an auth code back to the store which is then used to download sensitive API keys.

**Comment by abrookbanks** [comment]
I use a DDNS service to work locally @ www.brooky.com.

**Comment by Noodleyman** [comment]
> > I'm assuming that this is one of those modules which requires a FQDN accessible store?
> 
> Yes. PayPal needs to send an auth code back to the store which is then used to download sensitive API keys.

based on the error in the logs, it looks like it was received and sanitised. it crashed my web server and totally hung my sessions. I had to restart it :o

**Comment by abrookbanks** [comment]
No idea WTF caused that! We have quite a lot of merchants using this now.  No _known_ issues.
