### ISSUE TITLE
Merge customers

### ISSUE THREAD

**Issue by bos4711** [cubecart/v6#2489]
More than once time the same users have registered multiple accounts. That is, same physical shipping address, only the email address is changed. This was not a problem in the beginning, but it's starting to be. The ability to merge all these duplicates would save a lot of confusion in the long run.

I'm thinking something like this:

1. Select a customer (no 1)
2. In the customer, a tab / button "Merge" will be seen.
3. Clicking "merge" will open a request to enter the name of another customer (no 2).
4. Are you sure? (Y/N)
5. Merge will copy all orders from no 2 into no 1, and then delete no 2.

**Comment by bhsmither** [comment]
A follow-on step would need to be an email sent to the customer advising of this action.

The **customer should realize** that with a new email address (as new account), the purchase history of the prior account is not available. But if not, the email should mention both emails being used, and which one the admin gave priority to. Also include a link to reset the password, if starting to use a new email was only because they forgot the first one.

Aside that, I can envision two separate accounts having the same shipping address -- husband/wife, for example. Separate cost centers of a business, for another example.

**Comment by bos4711** [comment]
> Separate cost centers of a business, for another example.

Fair point. I did not consider that. However, for my particular case, I have about 5-10 unique customers that have atleast three accounts (different emails). I am not sure why they have done this, but it is clear it's one single user per multiple account so a merge would be beneficial for everyone.

I think.
