### ISSUE TITLE
Error from AIOS plugin

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#2563]
Quite often see this across multiple sites and doesnt seem to make a difference as to how zones are configured

[04-Aug-2020 11:05:47 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/XXXXXXXX/public_html/modules/shipping/All_In_One_Shipping/shipping.class.php on line 46

**Comment by bhsmither** [comment]
This happens when a customer reviews a past order.

The AIOS module is instantiated and does its `__contruct()` method. The boolean `false` is passed in for `$basket`, yet there is code here that wants to iterate through the basket `'contents'` - which is not set. In fact, nothing is set. All statements wanting to pull data from `$basket` needs to ternary test for `isset()` defaulting to empty values.

The specified shipping module (as recorded when the order was made) is called so that a properly formatted shipper's tracking URL can be given to the View Orders template. (AIOS will return _false_ instead of a URL, but that's beside the point.)

**Comment by abrookbanks** [comment]
Thanks. Fixed for 1.0.18 release due later.
