### ISSUE TITLE
Download Custom Path

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#261]
Just to confirm:

In CC6, there is no longer a download_custom_path?

So, there a means to assign files to a digital product where the digital file is "outside" of the 'public_html' folder?

**Comment by abrookbanks** [comment]
There should be! :)

![screen shot 2015-02-23 at 08 39 19](https://cloud.githubusercontent.com/assets/4520803/6324833/85219518-bb37-11e4-9d57-57ffb5ed8ebf.png)

**Comment by bhsmither** [comment]
Sorry for the lack of clarity. I am referring to admin, Store Settings, Stock tab, "Custom root file path" found in CC5 but not in CC6 (if I got that right).

I have something of an explanation here:
https://forums.cubecart.com/topic/48371-digital-download-locations/

**Comment by abrookbanks** [comment]
Ah I see. Yes it was removed.I thought it was unnecessary,  confusing and unlikely to be used.

**Comment by abrookbanks** [comment]
I'm going to keep this at the back of my mind. If demand is there I'll bring it back and reopen this.

**Comment by goodwinj** [comment]
Al, I'm not by any means a CC or a security expert but I'm aware that there are significant security advantages to be had by storing digital product files outside the public_html folder. 
The decision to remove Custom Root File Path not only means I have to reconfigure my store but also may not be as secure as before. I have been a CC user since version 3 and have not found Custom Root File Path to be "unnecessary, confusing and unlikely to be used." - quite the reverse, I've found it to be highly necessary, easy to use, and used for every download (in three stores).

https://forums.cubecart.com/topic/49723-digital-downloads-not-working/ 
covers this discussion, including some good comments from bsmither.

Although I may be a lone voice in the wilderness, can I appeal your decision to remove Custom Root File from CC6 and request it's re-instated in a future version?

**Comment by abrookbanks** [comment]
There are no security (or intellectual property) issues as your files are protected from direct public download by this file: https://github.com/cubecart/v6/blob/master/files/.htaccess

**Comment by abrookbanks** [comment]
... So long at it exists and you have a Linux operating system with Apache web server.
