### ISSUE TITLE
3rd parameter with _a is removed

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#2612]
e.g. 
https://demo.cubecart.com/cc6/index.php?_a=value1&b=value2&c=value3

Redirects to:
https://demo.cubecart.com/cc6/index.php?_a=value1&b=value2

**Comment by bhsmither** [comment]
Can you please elaborate on what action `_a` is doing?

**Comment by abrookbanks** [comment]
The download URL from the email for digital downloads is in the format.

?_a=download&accesskey=xxx

I wanted to add a parameter.

e.g. ?_a=download&accesskey=xxx&stream=1

It redirects back to;
?_a=download&accesskey=xxx

At this moment in time I have no idea where or why but I'd guess it's something in the SEO class.

Maybe something to do with seoable method. I'll have a deeper look when I'm back in the office tomorrow. $match[6] from a preg_match maybe.

**Comment by bhsmither** [comment]
Not finding it in CC629.

If `FileManager->deliverDownload()` does not error, CC exits with the browser staying on the downloads page, or a blank page if having clicked on the link in an email.

If it does error, I get taken to the customer's downloads page or the login page. Adding and keeping a third parameter is irrelevant.

Must be in some new code of yours because my trying the online demo doesn't do as you describe (maybe any changes to the demo code was reset?).

**Comment by bhsmither** [comment]
Found it.

In `SEO->__construct()`, there is this:
```
if (!in_array($match[2], $this->_ignored)) {
```
The URL is having `$match[6]` appended with a question mark.  Then `httpredir` is mangling that.

The key fault (IMO) is that the URL matches the `PCRE_REQUEST_URI`, but `$match[2]` cannot be found in `$this->ignore`. The `_a=download` URL **must** be found in that array.

Suggest adding to the array `private $_ignored` the value `'download'` (alongside `'downloads'`).

**Comment by abrookbanks** [comment]
Thanks. You have saved me a lot of time.
