### ISSUE TITLE
HTTP 400 with PayPal Commerce module

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#2734]
newly installed PayPal commerce module, version 1.3.23.  Linked with a PayPal account but unable to checkout via storefront.

Captured the following URL being called which throws a HTTP 400 error.

https://www.paypal.com/sdk/js?client-id=&merchant-[id=###&currency=USD&intent=capture&commit=true&components=buttons,hosted-fields ](url)

Note: I've only replaced the merchant-id with ### in the above URL.

The URL is returning:
```
throw new Error("SDK Validation error: 'Please pass a value for query param: client-id'" );

/* Original Error:

Please pass a value for query param: client-id (debug id: f9144f2b7c8fb)

*/
```

As the error implies, the client-id is missing/empty in the URL. I've no idea why, wondered if this has been seen before?

**Comment by abrookbanks** [comment]
I've seen this before. It's because the onboarding isn't complete. Disconnect and try again. The button used to connect to PayPal should load a small modal window not load a new browser tab. If there is a new browser tab then there will also be a JS security error. This may happen on websites that are not hosted as the primary name. The server header hostname doesn't match the domain. 
e.g. Say we have example.com at public_html and example2.com at public_html/example2.com example2.com may fail due ti JS security issues. 

A work around is to login to admin via master domain. e.g. https://www.example.com/example2.com/admin_xxx.php it will then pass security and onboarding should work and load in a modal window.

**Comment by Noodleyman** [comment]
Modal loads fine, no security error.  working theory is that you can't use the same PayPal account to link multiple stores. we got it working on the first one OK, but the additional stores seem to not work. the onboarding process seems to complete successfully.

headers are correct and not deployed the site into a subdirectory as per example URL

**Comment by abrookbanks** [comment]
Did they click the final blue button to return to CubeCart? That's vital to post back client ID etc..

**Comment by Noodleyman** [comment]
I believe so as the same steps were followed on the first site which is working correctly. However, I'll double check to confirm.

**Comment by abrookbanks** [comment]
Very odd. I haven't seen this before. Try onboarding again.
