### ISSUE TITLE
Database Use of stripslashes Kills nulls (was "Database Import to another DB Bug")

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2770]
Hey all,

I exported the database from the CubeCart Admin section under Advanced -> Maintenance -> Backup tab and under data Backup, I put tickboxes on all of them apart from Compression.

Once backed up, I copied the .sql file across to my new web host, Then imported it but it fails halfway with this error:

`Error in query (1366): Incorrect integer value: '' for column `xxxxxxxxxx_db`.`xxxxxxxxxxx_dbCubeCart_admin_users`.`customer_id` at row 1`

The customer_id is showing ''

The database structure for xxxdbname_dbCubeCart_admin_users for customer_id is

int(10) unsigned NULL

and my data has this line, snipped the rest:

INSERT INTO `xxxxxxx_dbCubeCart_admin_users` VALUES('1', '', '1', 'Tony', 'admin', ............................

When I updated the exported .sql database to show the customer_id from '' to '1' for xxxdbname_dbCubeCart_admin_users - the import worked.

But it also continues for other things

Error in query (1366): Incorrect integer value: '' for column `xxxxxxxx_db`.`xxxxxxx_dbCubeCart_documents`.`doc_url_openin` at row 1

and a few others.

Additional info: Exported from MySQL and importing to MariaDB. MariaDB is forked from MySQL so it should have worked,

Is this a bug?

**Comment by tonyrsutton** [comment]
Update:

Exported via phpMyAdmin and then imported to another DB - it works perfectly!

Does it mean there is something weird with CubeCart DB export from it?

**Comment by bhsmither** [comment]
I ran into that as well and I swear I posted an issue about it. But I cannot find it.

Please let us know what version of CubeCart you are making the backup from.

**Comment by bhsmither** [comment]
When I installed, via setup, CC629, the 'customer_id' column took on the default value _null_. When I installed, via setup, CC642, the 'customer_id' column took on the specific value **0**. I have yet to find where the difference took place.

Technically, the null that is returned from a SELECT statement should stay that way.

What I think is happening is that the null is not surviving PHP's fwrite() function. I cannot find much info regarding this specific situation. Another possibility is that it is not surviving the sqlSafe() function -- but I doubt that.

HeidiSQL will output an unquoted `NULL` instead of a zero-length-string (`NULL` is the correct thing to do for a text file, sometimes `\N` for a CSV).

**Comment by tonyrsutton** [comment]
Was exported (via the CubeCart admin) based on this version

CubeCart - v6.4.2
PHP - 5.6.40
MySQL - mysqlnd 5.0.11-dev

Imported to another web host which are

CubeCart - v6.4.2
PHP - 7.4.13
MariaDB - 5.5.5-10.3.27-MariaDB

**Comment by bhsmither** [comment]
Using phpMyAdmin, examine the table CubeCart_admin_users.

Are any of the values for 'customer_id' something other than a numeric value?

**Comment by bhsmither** [comment]
Found it.

The database class sends values through `sqlSafe()` and DB->strip_slashes(), both of which uses PHP's `stripslashes()` function.

PHP's `stripslashes()` **accepts a string and returns a string**. That means, when sending any other type of variable (integer, double, boolean, null, etc), PHP will first try to convert the incoming variable type to a string.

According to:
https://www.php.net/manual/en/language.types.string.php#language.types.string.casting

> **null** is always converted to an empty string.

The fix is to rewrite these two database functions to skip over _null_ values.

You might want to change the subject of this post to "Database Use of stripslashes Kills nulls"

**Comment by tonyrsutton** [comment]
Good find. As requested, I have renamed the subject of this post.

**Comment by tonyrsutton** [comment]
Thank you Al.
