### ISSUE TITLE
Feature Suggestion: Cubecart CHMOD/Permission Checker within Admin console

### ISSUE THREAD

**Issue by tonyrsutton** [cubecart/v6#2780]
Hey all,

Reading in the forum made me think...

I think it would be awesome if within the Admin page, maybe under Advanced -> Maintenance, there is a CHMOD/Permission Checker where upon clicking it, it will run the permission checking on all valid files and ensure they are all set up with the correct permission/CHMOD configs and if it found some incorrect setup, it offer you to fix it either by clicking 'Yes' or fixing it yourself.

This way, we can ensure that all CubeCart installations are as secure as possible & reduce attacks, etc.

Yay or nah?

**Comment by havenswift-hosting** [comment]
There is already this https://www.cubecart.com/extensions/plugins/cubecart-security-suite which does some basic checks.

Checking file permissions is complex because it all depends on how the hosting server is setup although this plugin could add functionality to check if a file or directory is 777 which either means permissions are set incorrectly in a secure environment (which could be fixed) or more likely the hosting server is running in an insecure mode in which case they couldnt be changed (although the customer could be recommended to move to a different / secure hosting company)

If people care about their shops whether that be from a security point of view or simply having support techs that know and care what CubeCart is, then store owners should not be using the cheapest crappy generic hosting they can find

**Comment by abrookbanks** [comment]
This is a simple PHP function that could be used. 
https://www.php.net/manual/en/function.is-writable.php 

Ian is right though. This shouldn't be necessary on a well configured server.

**Comment by tonyrsutton** [comment]
Make sense. Thanks all, I will close this.

**Comment by abrookbanks** [comment]
Cool thanks Tony. 😃
