### ISSUE TITLE
More Info to be in Min Qty Error Message

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#2798]
During checkout, if a customer changes the quantities of several items in the basket such that for any quantity that violated the limit, the error message does not indicate which item(s) need correcting.

Suggest that `Language->catalogue['error_minimum_quantity']` have a second placeholder for the product's name.

**Comment by abrookbanks** [comment]
I agree this would be much better. I have mountains to catch up on so I have to put this down as a feature request for now. Kids are finally back at school and I'm starting to realise the volume I have to catch up on. Strict bugs for now. 

At least I can put more time back into CC now instead of just firefighting.
