### ISSUE TITLE
Product folders vanished

### ISSUE THREAD

**Issue by cacaokingdom** [cubecart/v6#2938]
Been using Cubecart for a couple years without issue. Recently we had a complaint that our webpage wasn't working. When we checked, we found that all the product pages returned a 404 not found error. The individual products did the same. The about us page did the same. When looking through the folders on the server, it appears that the product folder is outright missing.

When I went into the Admin page, all the products are still listed and editable but if I click on the link to view the item in the page, it 404's. Is there any way to fix this short of dumping the entire install and reinstalling? I really dislike the idea of having to setup everthing all over again but that is the direction I am heading at this point to get us back up and online.

As an oddity, when on the home page, there are a number of our products visible. While we can't go to their specific pages, they CAN be added to the shopping cart. It is a really odd situation.

**Comment by bhsmither** [comment]
This caused by a change in how the URLs are derived. CubeCart creates "search engine friendly" URLs and up until the very latest versions, those friendly URLs ended with `.html`. (There is no folder containing product pages. Everything is constructed from data pulled from the database, populating templates. The Homepage works because the filename of the homepage is `index.php`.)

Well, not anymore. Now, friendly URLs do not end with anything.

However, you can force CubeCart to use the `.html` suffix. That setting is in Store Settings, Search Engine tab, "SEO URL Extension", choose `.html`.

**Comment by cacaokingdom** [comment]
I changed the SEO URL settings and the result was the same. Still get 404 errors for anything but the home page.

Should note that this isn't from using any external links but by clicking on items on the home page. Other than the home page, at this point my entire site is dead in the water. It happened a little while back but I hadn't had time to really mess with it and so far our site hadn't been a huge sales driver. Our store has received some attention locally and it has started driving more website visits.

**Comment by bhsmither** [comment]
I would really like to continue discussing this in the forums.
```
https://forums.cubecart.com
```
But, to eliminate one thought, there may be the need to review the database after having made an upgrade.
