### ISSUE TITLE
Cart totals after Customer logout

### ISSUE THREAD

**Issue by sumwonlost** [cubecart/v6#3030]
If Customer (logged-out) and Add to Cart, the amount display (next to cart icon), when Customer Log-in) it also display.  Now Customer decides to Logout, it no longer display, but if Customer Log-in again, it display again.

It need to display again even if Customer decides to Logout as items are still in Cart

**Comment by bhsmither** [comment]
When the customer *logs out* (and this applies to the admin logging out as well), CubeCart *destroys* the cookie-based _session_. Thus, there is no way for CubeCart to know who is actually visiting the store (and using the IP address is not a reliable method of session persistence) because the cookie being used will be different.

CubeCart does save the logged-in customer's shopping basket in the database (keyed to the 'customer_id') so that when the customer logs in again, even when using a new cookie, their basket is restored.

Curious to know of a use case where a customer _is required to log out_ yet also requires CubeCart to maintain session persistence - to show cart contents.

**Comment by sumwonlost** [comment]
Thanks for explanation.  Ok.  If customer comes back after 2 days and login, items are in basket.  However if customer firstly adds more items to cart then login, only the last items display in cart and not others previously added.  It should display all items until customer removes them.
