### ISSUE TITLE
Dashboard graphs sometimes load badly

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3146]
<img width="1312" alt="Screenshot 2023-01-27 at 07 44 18" src="https://user-images.githubusercontent.com/4520803/215039652-7dec1b2d-4243-4cc0-9e5d-edd0334568a3.png">

**Comment by bhsmither** [comment]
This is what I did:
```
Line 30, from
var chart = new google.visualization.LineChart(document.getElementById('chart_div'));

To:
var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));

**Comment by abrookbanks** [comment]
You are my hero.

**Comment by abrookbanks** [comment]
It still happens on some page loads.

**Comment by abrookbanks** [comment]
Hmm. The div is 100% width so the content in it we don't control is the problem. 
<img width="1432" alt="Screenshot 2023-01-30 at 08 49 34" src="https://user-images.githubusercontent.com/4520803/215430198-92f6ed20-df89-43af-a019-1247ee833a39.png">

**Comment by abrookbanks** [comment]
I can't find a reliable solution.

**Comment by bhsmither** [comment]
It has never been a problem for me.

But then, I am not putting height and width in `options`.

**Comment by abrookbanks** [comment]
Which browser do you use?

**Comment by abrookbanks** [comment]
Chrome has this issue.

**Comment by bhsmither** [comment]
Firefox.

**Comment by tonyrsutton** [comment]
I can confirm this is an issue for me on Chrome.

**Comment by bhsmither** [comment]
I used the new code as specified here:
```
https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code
```
and chose ComboChart. Google sends a LineChart instead.

A ColumnChart works fine.

**Comment by abrookbanks** [comment]
I tied the combo chart and has the same issue.

**Comment by bhsmither** [comment]
From above, you tried 'Combo' or 'Column', having the same issue?

I actually think it has to do with the declaration, or lack thereof, of how one wants the data to be visualized.

What more than one series of data do you hope to show as a combo? Monthly sales split across two years, but what else?

**Comment by bhsmither** [comment]
Try this with the ComboChart:
```
           var options = {
             seriesType: 'bars',
             title: '{/literal}{$CHART.title}{literal}',
           };
```

**Comment by abrookbanks** [comment]
Everything I've tried causes it still. The div is the correct size but Google is rending the internals for it with wrong sizes. A 100% width could be for example  have a set width inside of 400px.
<img width="1559" alt="Screenshot 2023-02-01 at 09 38 12" src="https://user-images.githubusercontent.com/4520803/216006731-c0c8e0b7-e68d-420a-9354-7c8da896ea77.png">

**Comment by bhsmither** [comment]
Did the `seriesType: 'bars',` get added to the javascript code?

And why is the graph data always changing? (Taking screen grabs of installations other than your developer instance?)

**Comment by abrookbanks** [comment]
The last screen grab just happened to be on a customer store I was on. I'll do some more tests with combinations of the options here..

**Comment by Lastwolf1882** [comment]
I found that if you refresh the dashboard page you can get the bad chart size and if you resize the browser window even momentarily and refresh, you get the intended chart size

**Comment by abrookbanks** [comment]
Yes I've experienced the same.

**Comment by Lastwolf1882** [comment]
Can replicate every time on Chrome and Chrome based browsers (Vivaldi and Edge) by Ctrl+F5-ing on the dashboard. Can't get firefox to do it at all. (On Windows 11, if that matters)

**Comment by abrookbanks** [comment]
Thanks @Lastwolf1882 that inspired me. This is now resolved.

**Comment by bhsmither** [comment]
I (finally) saw this on my Firefox. It happened twice among a couple dozen browser window (viewport) width resize/reload tests, but only when reducing the width, never increasing (but maybe a lot more tests would have shown that). (However, this might not even be relevant.)

The theory that some have regarding this is that the 'container' where the chart is located is not detectable (display:none) by the javascript. This is caused by a race condition between when the tab panel content becomes visible and running the chart loader script.

You can deny this race condition by commenting out lines 715-724 in admin.js.
```
714: $("div.tab").each(function() {
/*
...
*/
725: if ($("#wikihelp").exists()) {
```
This prevents showing any tab_content by default.

Now, click the 'Dashboard' tab. Thus, that tab's content gets shown. 

Because the chart's javascript has already drawn the chart, but had no idea how big to make it, defaulted to 400x200px.

The CSS has a rule `div.tab_content{display:none;}`.

Suggestions on StackOverflow recommend executing `chart.draw()` someplace where the chart's container is detectable by the javascript.
```
https://stackoverflow.com/questions/56846846/why-google-charts-width-not-working-when-change-display-from-none-to-block
https://stackoverflow.com/questions/14304972/google-chart-default-size
```
