### ISSUE TITLE
Allow admin access to store while offline? Checkbox

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#33]
Intentionally deleted, missing?

**Comment by abrookbanks** [comment]
Intentionally missing. Staff should be able to preview the store whilst offline to check their work. All these things are open for debate but I can't see any reason why the old functionality would want to be used to switch it off.

**Comment by Dirty-Butter** [comment]
Me, either. Just checking. Thanks.

**Comment by abrookbanks** [comment]
Cool! Ok this is closed but open for comments still. At the end of the day if people want it to work a certain way we'll make it happen.

**Comment by bhsmither** [comment]
I vote for coding the store as "open" for logged-in admins.

Similarly, I vote for coding the skin selector as visible for logged-in admins -- so that alternate/custom skins can be worked on without the need to "close" the store -- as would be necessary when the configured skin must stay and not let the customer be able to change it.

There are other store settings. Perhaps a companion tab to **Featured** and **Layout** that would be for **Development**. Duplicate all these frontside settings but apply for only logged-in admins.

**Comment by abrookbanks** [comment]
![screen shot 2015-01-12 at 18 21 34](https://cloud.githubusercontent.com/assets/4520803/5708318/de4b59ec-9a87-11e4-8272-ce5fa0c99a04.png)

**Comment by abrookbanks** [comment]
Done.
