### ISSUE TITLE
Q: Why This Edit?

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#3366]
In https://github.com/cubecart/v6/commit/9acf62439d8ca070109d823237d4ca850686ae13, is this edit related to the new search engine ElasticSearch?

**Comment by abrookbanks** [comment]
I'm not totally sure what was going on here. In the json-0ld markup we have. 

```
{"@type":"SearchAction","target":"{/literal}{$STORE_URL}{literal}/search{/literal}{$CONFIG.seo_ext}{literal}?search%5Bkeywords%5D={search_term}&_a=category","query-input":"required name=search_term"}}
```

The search URL was showing up as an error in the system error log complaining about {search_term} I think. The bit of code in that commit just prevents it from searching on that term. I don't really know whats going on because I'm sure the markup is correct.

**Comment by bhsmither** [comment]
Might be related to #3232.

**Comment by abrookbanks** [comment]
Yes. The syntax is correct I'm sure. 🤷🏼‍♂️

**Comment by abrookbanks** [comment]
Closing for now.
