### ISSUE TITLE
Permissions over skin directory

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#348]
These should now be writeable otherwise you can't use the auto install feature in the market place without changing your /skins/ folder permission first.

The installer doesn't check for this.

**Comment by havenswift-hosting** [comment]
Or simply recommend not using a hosting company that uses the DSO php handler where 777 permissions are needed on directories that need to be writeable.  suPHP or fcgi with suExec should be a requirement for CubeCart for security when all directories can be 755 but more importantly, you have a secure hosting environment rather than the one that the hosting company can cram as many sites onto

**Comment by abrookbanks** [comment]
This is true.. most hosting companies this should just work with... at the same time if it doesn't an error will be shown. Maybe it should be made writable on install.. need to think about this.

**Comment by havenswift-hosting** [comment]
You cannot simply force directories to be 777 on all installations as that introduces security issues. If you can detect whether the skin directory is writeable as you do with other directories and indicate this, then you can 1) warn people that their hosting is insecure and 2) give people instructions on making these directories world writeable if they really want an insecure system !

**Comment by hairydogltd** [comment]
There are other ways to achieve the same result. I am not a fan of imposing solutions. Provide the requirements and maybe advice about how to meet them. 

I'm not sure there is a problem with the skins directory being 777 on install, as long as it is changed afterwards, at the same time as removing the setup directory. 

There is a pre-install script that checks that the correct directories are writeable. Perhaps there should be a post-install script that checks that the permissions are not too wide?

**Comment by havenswift-hosting** [comment]
>>I'm not sure there is a problem with the skins directory being 777 on install, as long as it is changed afterwards, at the same time as removing the setup directory.

The point is that any directories that need to be 777 in order to be writeable need to be left at those permissions to keep it that way in order to use auto installation from the marketplace.

>>There is a pre-install script that checks that the correct directories are writeable. Perhaps there should be a post-install script that checks that the permissions are not too wide?

It has nothing to do with permissions at installation time.  If you are using a hosting company that is using the DSO PHP handler then any directories that need to be writeable have to be world writeable at 777 all the time.  As I have said this is purely down to greed from the hosting company as this takes the least server resources but opens up your account to major security issues.  If there is a security issue with ANY other account on the server, then your hosting account is wide open to being hacked.

**Comment by hairydogltd** [comment]
I am not a fan of imposing solutions. Provide the requirements and maybe advice about how to meet them. 

Leaving autoinstall from the marketplace available on a production system seems very foolish to me.

**Comment by Noodleyman** [comment]
Just a thought :)

can the auto installer change to 777, do the install, and change back to the original value?

**Comment by abrookbanks** [comment]
It will use the lowest possible CHMOD value for the server on question. 

includes/functions.inc.php
```
/**
 * Get writable chmod value
 *
 * @return string
 */
function chmod_writable() {
	if (!defined('CC_CHMOD')) {
		//Fall back mode
		$mode = 777;
		if (function_exists('posix_getuid') && function_exists('posix_getgid')) {
			//Same user
			if (fileowner(__FILE__) === posix_getuid()) {
				$mode = 755;
			//Same group
			} else if (filegroup(__FILE__) === posix_getgid()) {
				$mode = 775;
			}
		}

		if (is_writable(CC_CACHE_DIR)) {
			$tmpdir = CC_CACHE_DIR.'/'.'chmodtmp';
			mkdir($tmpdir, octdec((int)$mode));
			if (!file_exists($tmpdir)) {
				trigger_error('Error checking CHMOD', E_USER_ERROR);
			}
			if (!is_writable($tmpdir) && $mode != 777) {
				//Fall back
				$mode = 777;
			} else if (!is_writable($tmpdir)) {
				trigger_error('Cannot detect proper CHMOD', E_USER_ERROR);
			}
			rmdir($tmpdir);
		}
		define('CC_CHMOD', octdec((int)$mode));
	}
	return CC_CHMOD;
}
```

**Comment by abrookbanks** [comment]
The plugin install tool will error and ask the user to make the folder writable. Lets see how this goes.. It may be that we need to do something but time will tell. For now lets leave this as is.
