### ISSUE TITLE
CKEditor Bug <!--{cke_temp_3964703717}

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#3573]
The rich text editor seems to be corrupting some HTML code. 

e.g. 
```
<html>
<head>
    <title>Store Closed</title>
    <meta http-equiv="Refresh" content="0; url='https://example.com/store-closed.html'" />
</head>
<body>
<p>Store Closed</p>
</body>
</html>
```

After saving, it was replaced with this:

```
<html>
<head>
    <title>Store Closed</title>
    <!--{cke_temp_3862409646}
</head>
<body>
<p>0--&gt;</p>

<p>Store Closed</p>
</body>
</html>
```

**Comment by bhsmither** [comment]
Does #3427 apply?

No. This is something new.

It probably (but not verified) still only affects a `class="fck-full"` type editor, because there may be nesting rules applied to the `<head>` section.

No, happens everywhere. But the experiment is using a tag that may be illegal (not in CKEditor's permissable tags list): `<meta>`

**Comment by bhsmither** [comment]
I did post this:
```
https://github.com/ckeditor/ckeditor4/issues/4506
https://github.com/IGx89/CKEditor-ShowProtected-Plugin/issues/10
```
