### ISSUE TITLE
Issue with empty line orders

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#367]
Below is an example..

I expect that this is caused by items not being removed from the cart/basket if they are no longer in stock or available. Test needs to be made by placing items in basket... removing the item and placing the order. Hopefully that will reproduce this and appropriate fix can be made. 

![screen shot 2015-03-11 at 16 38 06](https://cloud.githubusercontent.com/assets/4520803/6616093/4c440118-c8a2-11e4-98bd-d2fcc3df9a0e.png)

**Comment by havenswift-hosting** [comment]
Al - this is the exact problem we have had with multiple customers over the past year and been the subject of multiple support tickets.  While it seem so happen irregularly and we werent anle to track down a way to reproduce it, it would be fantastic to get this fixed !

**Comment by abrookbanks** [comment]
Yeah. I just hope I can reproduce it..

**Comment by bhsmither** [comment]
I ran into this working with a site and traced out the code extensively. I reported it. Probably back when I was submitting sales tickets.

The problem I discovered was that if there was only one item in stock, and the store settings is set to reduce stock on Pending, then when the cart is tabulated during checkout, there is no item to show and what does get shown is one each of nothing.

**Comment by bhsmither** [comment]
Sales Ticket `#97830`.

**Comment by havenswift-hosting** [comment]
Brian - that sounds entirely logical to me and on checking the various clients that have previously reported this problem, they are all reducing stock levels on Pending. I know that there are some rare circumstances where this is the best choice but generally for stores, we almost always recommend reducing when changed to processing so that is why there is only a handful of people that have reported it

**Comment by bhsmither** [comment]
The screen grab above doesn't indicate what its a screen grab of. The admin Order Summary? The email?

**Comment by hoobu** [comment]
Hi, 

The screen grab is from the admin view showing the order, we get this allot as our clients products are fast selling and low stock, I am going to do some more tests myself and will post any findings. 

Thanks 
Matthew

**Comment by Noodleyman** [comment]
I've also seen this in CC5 with three other live stores, it's been lurking a while. never been able to reproduce it or figure out the root cause! I know of several people who would love to get to the bottom of this issue.

**Comment by bhsmither** [comment]
My earlier extensive tracing out of this problem has narrowed the likely place the problem occurs is at `Catalogue->getProductData()` that returns a `false` because the `Catalogue->outOfStockWhere()` returns a WHERE clause that specifies the item being looked at must be in stock - which it no longer is.

When reviewing the order's details (in admin(?) and in the email sent), a call is made to `Order->getOrderDetails()`. In a loop `foreach ($this->_order_inventory as $item)`, this call is made:
`array_merge($GLOBALS['catalogue']->getProductData($item['product_id']), $item);`
`array_merge()` returns a PHP fault because argument-1 is not an array.

Thus, a line item with nothing in it.

Regardless the purpose of fetching the item's details from the database when we already have most or all of it in the `$_order_inventory`, we should keep it *as is* for the hooks' sake.

I would suggest instead of PHP's `array_merge()`, we use CubeCart's `merge_array()`. But `merge_array()` needs to be fully tested at this location.

**Comment by abrookbanks** [comment]
Evidence of items not being removed from basket when no longer available.

![screen shot 2015-03-16 at 08 52 38](https://cloud.githubusercontent.com/assets/4520803/6662996/e58e203c-cbb9-11e4-91d2-7177dbc6d20c.png)

**Comment by abrookbanks** [comment]
Above fix works really well and can be applied to v5 in the same way. Result below...
![Uploading Screen Shot 2015-03-16 at 09.04.47.png . . .]()
