### ISSUE TITLE
Test XCache with default config

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#374]
See issue https://forums.cubecart.com/topic/49418-warning-xcache-isset-xcache-var-cache-was-not-initialized-properly-check-php-log-for-actual-reason-in-varwwwccclassescachexcacheclassphp/?p=206786#entry206786

**Comment by havenswift-hosting** [comment]
The initial problems reported in the thread are due to some XCache configuration settings which are part of the installation / configuration of XCache not being set but I can confirm that this is an issue with XCache and CubeCart

Warning: xcache_isset(): XCache var cache was not initialized properly. Check php log for actual reason in /home/cubecar2/public_html/classes/cache/xcache.class.php on line 154

**Comment by havenswift-hosting** [comment]
As I commented on the forum thread last night, I dont believe this is a CubeCart error.  It is simplt a warning that certain variables havent been set at all from default installation values of zero which means XCache cannot effectively work.  Required settings are for xcache.size and xcache.var_size which need to be non zero.  This is an initial setup task (although these and others can need tuning depending on server load)
