### ISSUE TITLE
Extensions need version notifications

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#387]

**Comment by Dirty-Butter** [comment]
Today's USPS change makes this a definite must have!! Even a notice on the Plugin page in Admin probably isn't enough. I know I don't normally look at that section once all is set up the way I want it. I would suggest a notice at the top of Dashboard, just the way CC upgrade notices are given, for any plugins in the folder - enabled or not. I would say include upgrade notices for disabled plugins in the admin list, too, because the upgrade might make a disabled one useable again.

**Comment by Noodleyman** [comment]
@abrookbanks, where is this on the roadmap? It's a really powerful feature but would greatly improve the link between marketplace, stores and module updates.

**Comment by abrookbanks** [comment]
The problem is I can't see any way existing plugins can check the version. It looks like I can only build this with changes to the marketplace that once launched allow plugins to check version installed after this time. I REALLY want to launch something that works with the data we already have. It may be possible by reading the version number in the config.xml file of each module then checking against the server but I'm not sure there is a way to identify it on our server or whether 3rd parties have been using the version field of the XML file. 

I think the only option is to build something new.

**Comment by Noodleyman** [comment]
How about this:
in the marketplace, on a per product basis, can a seller maintained version table be added? This allows the seller to define their own version numbers and release dates. That can have a sequence / order, or simply be ordered by release date, newer to older to find the most recent version.

Since this is a "per product" list, the verion number system doesn't matter for the plugin. For example I like to use the format "1.0.0", but others may use "1.0". The table would support both, as it only cares about the dates..

The version number can be pulled from these tables via the store using an RSS / XML call and notices on the dashboard if the installed plugin version (from config.xml) does not match the most recent version in that feed.  You can even add an option for the seller to toggle a checkbox on/off to notify customers of updates. 

Should be quite simple to setup and impliment.

**Comment by abrookbanks** [comment]
There needs to be a means to identify the extension from the CubeCart shop. Ideally we would take the extension ID but as of now there is no means to get this. The only way would be to either capture it with extensions auto installed with the token or somehow write it into the config xml file. 

Right now there is no way to connect an extension to the marketplace.

**Comment by Noodleyman** [comment]
within the module, config.xml
Matching on "uid", "type" and "folder". Those pieces of information can be matched via configuration within the marketplace. Any seller of a module should know these pieces of information as they would have had to define them in their module.

**Comment by abrookbanks** [comment]
This is a duplicate and has been implemented for version 6.1z
