### ISSUE TITLE
Foundation Mobile Site Category Page missing categories

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#403]
If you view the demo of your store on a mobile and press "Shop by Category" then "TV & Home Cinema" then "TV & Home Cinema" again it should show all the sub-categories LED TV's, LCD TV's and 3D TV's but nothing shows?

**Comment by abrookbanks** [comment]
This is intentional as it takes up too much space on a mobile device. If you want them to show open the file:
skins/{skin name}/templates/content.category.php and find:

```<ul class="small-block-grid-6 text-center show-for-medium-up" data-equalizer>```

Replace with:
```<ul class="small-block-grid-6 text-center" data-equalizer>```

You may want to change the amount of columns on small devices from ```small-block-grid-6``` to something like:

```<ul class="small-block-grid-3 "medium-block-grid-6 text-center" data-equalizer>```

More info here: http://foundation.zurb.com/docs/components/block_grid.html
