### ISSUE TITLE
Website Payments Pro & Express Checkout Bug??

### ISSUE THREAD

**Issue by ItsME1** [cubecart/v6#415]
When I click the "Secure Checkout" button, select the toggle button next to the images of the credit cards, then click the "Continue" button, I receive the "Many thanks for your order.  The order status is currently pending..." message without being prompted for credit card information.  I have verified that my API settings are correct and when I select the "Check out with PayPal button", it seems to work correctly.  I've tried re-installing the plugin and the problem persists. I verified that the Gateway Mode is set to Live and the Payment Action is set to Sale.  The order is listed under Orders with a status of Pending.  Does anyone have any suggestions as to how I can get this to work?

**Comment by abrookbanks** [comment]
Shame this bug wasn't reported sooner as 6.0.3 has literally just been released. I can reproduce this issue and will look into it.

**Comment by abrookbanks** [comment]
Forums post: https://forums.cubecart.com/topic/49473-does-website-payments-pro-express-checkout-option-work-in-cc-6x/

**Comment by ItsME1** [comment]
Thank you!

**Comment by hairydogltd** [comment]
Using the standard Paypal payments (running a skin based on a v5 skin) when you click to checkout and pay, there is a progress (grey barber's pole) bar showing no progress and asking you to wait. You can wait as long as you like: it never completes until you click the Proceed button.

Not sure if this is the same issue. Possibly not.

**Comment by abrookbanks** [comment]
No that's not the same issue. Please check for JS errors in your browser console. This has always worked in v5. There should be some JS to auto submit the form when the loading gif loads.

**Comment by hairydogltd** [comment]
The problem seems to be here:

jquery-migrate-1.2.1.js:21 JQMIGRATE: Logging is active
plugins.php:9 Uncaught TypeError: undefined is not a function

but also why is it looking for layout.css?

http://www.hx2.co.uk/store/skins/henry/styles//layout.css Failed to load resource: the server responded with a status of 404 (Not Found)

I've created an empty file by that name just to keep it happy!

**Comment by abrookbanks** [comment]
I've never heard of JQMIGRATE. Sounds like a customisations bug. I haven't looked at this actual issue yet but your issues isn't related.

**Comment by hairydogltd** [comment]
I've not heard of it either: I never use jquery. Line 9 of the plugins.php file seems to relate to the All in One Shipping plugin.Though I'm not sure how far you can trust line number references. This problem was the same before I updated to the latest version of the plugin. However, it does seem to be related to the skin mods because it works fine with Foundation and Kurouto (which my version is based on)

**Comment by hairydogltd** [comment]
Hmmm. Curiouser and curiouser. This was happening consistently on one PC, regardless of web browser. So I tried it on a different computer, and it seems to work just fine. Whatever the problem is, it seems to be related to that PC and that skin.

**Comment by abrookbanks** [comment]
For this fix to work you MUST also upgrade PayPal Pro to 1.0.4!!
https://www.cubecart.com/extensions/plugins/paypal-pro-express-checkout
