### ISSUE TITLE
Bxslider breaking - Bug

### ISSUE THREAD

**Issue by bondimedical3** [cubecart/v6#432]
I have noticed that if you move your mobile screen on the transition from the last slide to the first the whole slider stops. The issue is intermittent but persistent and nothing works, touch slide, left right navigation buttons etc?

**Comment by bondimedical3** [comment]
This issue has occurred on both my mobile and tablet

**Comment by bondimedical3** [comment]
I have noticed that the issue also occurs on http://bxslider.com/examples/multiple-slideshows so I have reported the matter on their Github

**Comment by abrookbanks** [comment]
Issue report here: https://github.com/stevenwanderski/bxslider-4/issues/787

**Comment by Tidal-Wave** [comment]
Hey there folks, Im the current dev for bxSlider and I would love to help out. Combing through the repo here I don't see bxSlider. What version of the slider are ya'll using? 4.1.2 had some issues with transitions on mobile devices, but those got cleared up in 4.2.1. I was brought into this project to maintain it for Steven, but I don't have control over the public website, so I can't update the download there. 

I am working on our next big update (4.2.4) and will have it available shortly. If there i still an outstanding issue I would love to get that fixed in this sprint.

**Comment by Tidal-Wave** [comment]
just as an update, I pushed the 4.2.4 WIP to our development branch today. It is stable, I just have a few more small milestone enhancements and some documentation updates to finish up.

**Comment by abrookbanks** [comment]
Hi @Tidal-Wave I had a look in the development branch but didn't see a 4.2.4 release. Is the latest build good to use instead for production environments?

**Comment by abrookbanks** [comment]
From testing it seems fine. Thanks! :)

**Comment by Tidal-Wave** [comment]
Just as an update, I have moved 4.2.4 to master. There where only a few small additions from the WIP, but please feel free to officially update.

**Comment by abrookbanks** [comment]
Thanks Eric. Top man!
