### ISSUE TITLE
Add to Basket on Category View doesn't Pass Quantity

### ISSUE THREAD

**Issue by NaturalSigns** [cubecart/v6#461]
I found this on my site but also occurs on CC6 demo store.  Hopefully picture below says it all.
![cc qty issue](https://cloud.githubusercontent.com/assets/10531097/7144296/82f891d4-e2dc-11e4-8a0b-feb974fa9d7c.png)

**Comment by bhsmither** [comment]
In the Foundation skin, for View Category, there are two major `<div>` blocks: `product_list_view` and `product_grid_view`. Each of these blocks have the necessary `<input>` tags. But...

`product_list_view` uses the correct structure for this page:
```
<input type="text" name="add[{$product.product_id}][quantity]" value="1" class="quantity text-center">
```
`product_grid_view` uses the wrong structure for this page:
```
<input type="text" name="quantity" value="1" class="quantity required text-center">
<input type="hidden" name="add" value="{$product.product_id}">
```
Technically, because each item is wrapped in a distinct `<form>` block, either structure will work. Probably the single `<input>` structure is a carry-over from CC3/4, or maybe it's that way so that having **all** items contained in one `<form>` block allows for an easier customization for a bulk add-to-cart action.

Anyway, because there are in effect two logically identical blocks of form elements, one being "hidden", where the hidden form elements should not be included in the POST. **But they are!**

In the default list view, we have for POST:
```
add[3][quantity]=5
quantity=1
add=3
```
In grid view, we have for POST:
```
add[3][quantity]=1
quantity=5
add=3
```
Probably, PHP dumps `$_POST['add']['3']['quantity']` when it accepts `$_POST['add']`.

The form submission is being handled by the "add_to_basket" function. According to the jQuery docs and the W3, hidden or invisible form elements may still be included.
http://www.w3.org/TR/html401/interact/forms.html#h-17.13.2

In order for jQuery.serialize() to **not include** hidden form elements, the function that hides one of the two blocks must also change the hidden form elements in a way so that they are not included, such as removing the `name` attribute, but that would require a `temp_name` attribute to switch it back on.

I think a simpler approach would be to move the `<form>` statements inside the list_view and grid_view `<div>` blocks, as such:
```
<div class="product_list_view">
  <form>
  </form>
</div>
<div class="product_grid_view">
  <form>
  </form>
</div>
```
Thus we have associated each `<input>`, one hidden and one visible, to its own parent form object.

**Comment by abrookbanks** [comment]
Thanks for your help here everyone. :) This works great now.

**Comment by abrookbanks** [comment]
Movie: http://static.cubecart.com/github-461-addtobasket.mp4
