### ISSUE TITLE
Text options not saving for options assigned by group

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#509]
As above..

**Comment by abrookbanks** [comment]
Maybe related:
"I’m on v6.0.4, and I’ve applied product options set to a load of products. However I am unable to change the individual entry statuses. It looks like they are all disabled, but they are not, they are enabled. Changing the setting does not apply. Is this a known issue and fixed in the next release? Screens shot shows what I mean."

![snipimage](https://cloud.githubusercontent.com/assets/4520803/7677766/e2943b64-fd46-11e4-8c84-f4d658b65aad.JPG)

**Comment by SemperFiWS** [comment]
I just mentioned the status issue here:
https://github.com/cubecart/v6/issues/517

I think this might be happening because when you assign manually, each option is added into the 'CubeCart_option_assign' table.
But when you assign via option set, they are not.

Instead the 'CubeCart_options_set', 'CubeCart_options_set_member' and 'CubeCart_options_set_product' tables are used.
None of these contain a 'status' field.
So as a result there is no method to have enabled/disabled options as part of an option set.

A quick solution would be to add and utilize a 'status' field in the 'CubeCart_options_set_member' table.

However, that is not a perfect solution as some stores use option sets for multiple products, but the status per product could vary.
e.g.
Product A
Has color options of black, white, blue and red.
These are set via an option set, all are currently available.
Product B
Has color options of black, white, blue and red.
These are set via an option set, but blue and red are NOT currently available.
Seeing there is no way of setting the status for each on a per product basis, all will shop up in the store.

Another related issue here is that if you set a products options via an option set, they cannot then be setup using the options matrix.

**Comment by abrookbanks** [comment]
I'm giving myself a serious round of applause here. This was a STINKER.
