### ISSUE TITLE
Foundation Skin - JS triggers on page load, but isn't needed

### ISSUE THREAD

**Issue by Noodleyman** [cubecart/v6#516]
Very minor, but something I spotted today.

When loading a product the jQuery function to set the option price + main product price = new price is triggered on page load.

It only needs to be triggered when an option is selected.

    if($('#ptp').length > 0 && $('[name^=productOptions]').length > 0) {
        price_inc_options();
        $("[name^=productOptions]").change(function() {
            price_inc_options();
        });
    }

**Comment by bhsmither** [comment]
Would this cause problems if a skin's code has a default optional accessory selected that affects the price? Such as, "Installation Service (+$10.00)" or "Upgrade Guarantee" as the default option chosen when the page loads.

Otherwise, as I have seen it sometimes, the product's price includes all the available optional accessories, then the customer has to deselect it all. Such as:
Installation Service:
* Yes, please
* No thanks (-$10.00)

**Comment by Noodleyman** [comment]
Thinking about it, yes that would stop it from working. Might need a minor enhancement to make it fire on page load if the options are radio buttons.

**Comment by abrookbanks** [comment]
So from what I have read nothing needs changing? I've closed this but will reopen if I missed something. Please let me know if you want me to look deeper.
