### ISSUE TITLE
Add Insurance and Signature Confirmation Choices to USPS Plugin

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#520]
See https://forums.cubecart.com/topic/49714-usps-allow-user-to-purchase-insurance-signature-confirmation/

FYI: May changes coming - http://www.endicia.com/usps/postage-rate-change/-/media/Files/usps/understanding-the-may-2015-usps-price-change.pdf

**Comment by Noodleyman** [comment]
It would also be good to add the Hazmat option as well.

**Comment by abrookbanks** [comment]
It doesn't look like any technical changes are needed for the price changes. I've put this down as a feature request.

**Comment by LaughingHorse1** [comment]
Actually, this is more of a crucial need. The info is already being pulled from the USPS website as I understand it. So it's just adding the ability to:
1. set the level where the insurance charges start
2. select the $ level where signature required is added.

This can either be the customer's choice at checkout (preferred)
Or a blanket for everything.

And when picking which number to choose, pick the full retail as opposed to the internet rate.

Right now on a package with a value of say $342 since CubeCart is not allowing for insurance and signature required there is a loss of around $8 in postage per shipment, which is substantial.

**Comment by abrookbanks** [comment]
There is no ETA for this so I'd recommend hiring a developer if it's business critical.

**Comment by tenaja** [comment]
Any chance this will get implemented? Without insurance, CubeCart is no longer an option for me. Thanks.

**Comment by Noodleyman** [comment]
if you get really stuck and it's having such a large impact, I can probably help you out with a custom commercial solution.

**Comment by tenaja** [comment]
Thanks for writing back.
Not having shipping insurance is a deal breaker for CubeCart. The reason I'm looking at switching to CC is because I don't have time to fiddle with osCommerce any more...and I'm not going to have time to fiddle with CC, either.

You'll probably find a dozen solutions in the osCommerce Contributions. The instructions will also be available in the USPS and UPS api documents. 

Let me know if you'd like to quote it. Cliff

**Comment by Noodleyman** [comment]
@abrookbanks ,

I did spend some time looking into this and I've written a manual way of adding the insurance for now, but it does need some work in the core module to add this standard feature.

The first issue is that the USPS module makes an API call to USPS using the "All" method. The module then loops the returns services and grabs the rate. The "All" method doesn't support insurance. To add insurance to the returned data you have to make an API call directly for that service with the required data for the insurance quote.

the USPS manual suggests that first an "all" call should be made to see which services can be used, then to make another API call for each of those valid services.  So, the module already does the initial part.

I think it needs the following:
1) A new checkbox in the USPS module next to each service to enable insurance. 

2) After making the "All" API call and filtering valid services, check which of those services has insurance enabled.

3) For each enabled service, do an additional API call with the requried data to gather an insurance quote. Calculate the shipping price inclusive of insurance.

I was going to look at doing this myself, but I honestly can't justify the cost of the time as it will take at least a few hours, if not a day to do properly.
