### ISSUE TITLE
Smarty Replace

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#596]
Regarding #587, the code that the setup upgrade SQL statement changes is still present in the /language/email_en-GB.xml file and the email_definitions file.

Not actually having tested for a faulting `{$DATA.element|replace:'_':' '}`, I just do not see anything wrong with that expression.

**Comment by abrookbanks** [comment]
Fixed with commit 64691fee4b98601ca7bf9fa57de62f741c20a078 for next release. See https://github.com/cubecart/v6/issues/587

The smarty code works but CKEditor destroys its integrity on save. I've spent hours trying to get Smarty and CKeditor to play nice. I got some code working to ignore smarty variables but then they just can't be seen to edit. I can't win with this.
