### ISSUE TITLE
Problem with CC Security Suite plugin?

### ISSUE THREAD

**Issue by Dirty-Butter** [cubecart/v6#685]
See https://forums.cubecart.com/topic/50020-cc-security-suite-and-ip-adresses/

**Comment by abrookbanks** [comment]
I've put this as "wontfix" but it's noted. I think there is a more general issue in that modules shouldn't be able to be turned on unless minimum settings have been made.

**Comment by bhsmither** [comment]
In the CCSS module file /admin/index.inc.php, `$create_table` contains within the string the database table prefix. That string is then sent to DB->parseSchema().

In parseSchema, there is a str_replace():
`'CubeCart_'` gets replaced with `$this->_prefix.'CubeCart_'`
Since the $query already has the table prefix, the strr_replace() prepends another to it.

Suggest not asserting the table prefix when sending queries to parseSchema().

Note: If DB->_prefix is empty, the names of the CubeCart tables are not changed. And neither is `{%DEFAULT_EN-XX%}`.
