### ISSUE TITLE
Inclusive tax needs to be calculated with quantity

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#724]
Issue:
1 x £0.49 item with 20% tax = £0.4083 = £0.41
100 x £0.49 item with 20% tax = £40.83

CubeCart works this out before quantity and will charge £41

**Comment by tbuschkuehl** [comment]
The problem is a rounding issue, not a calculation issue.

You used '%.3F' which only gives you 1/10 precision (i.e. 10 cents!!!) for a e.g. price of $10.67.

I have changed it to '%.9F' in the functions "get" (cart class) and "inclusiveTaxRemove" (tax class).

The display of the price is not adversly affected by this change, but the overall basket value is now correct.

Have only tested this for a hand-ful of cart-updates, not thoroughly tested for all sorts of scenarios, but seems to work so far.

Hope this helps.

**Comment by abrookbanks** [comment]
Thanks for your help here. I think that your findings may work in some situations but an adverse affect of this is under rounding in other circumstances.
