### ISSUE TITLE
Canonical problem / foundation skin

### ISSUE THREAD

**Issue by kealanm1** [cubecart/v6#727]
All categories appear to carry a variant which includes " ?page=all " at the end. In the foundation skin this does nothing but is being indexed by search engines. The canonical for these pages also includes the ?page=all so it is not correctly linking back to the category with no pagination and is being identified as a separate unique page. This is having a negative impact on overall site seo performance as duplicates are competing for positions.

**Comment by abrookbanks** [comment]
From my testing this does do something. It lists all the products in the category instead of the first x amount. However the "More \/" button shows when it shouldn't. I wonder is a no spider header should be added when page=all

I'm no SEO expert so not sure about that. It may well avoid duplicate content. Closed for now.. happy to reopen.
