### ISSUE TITLE
Instant Product Option Stock Check

### ISSUE THREAD

**Issue by abrookbanks** [cubecart/v6#75]
CubeCart need to display stock levels for product options prior to add to basket submit.

**Comment by bhsmither** [comment]
I think I got it figured out. An ajax call.

Just need to collect all the selected values, once all the productOptions have a non-empty value selected.

And figure out how to make an ajax call.

**Comment by abrookbanks** [comment]
Amazing! I was thinking along those lines too. Let me know if you need me to take a look. Top man! :+1:

**Comment by havenswift-hosting** [comment]
It isnt just about displaying stock levels for product options.  If stock levels are entered against options (or option matrix) then the following store settings should work : 

1) Show stock levels - this should show the stock level for that option combination
2) Allow out-of-stock purchases - self explanatory
3) Hide out-of-stock product - if a product option is out of stock, then the combination should not even be shown in dropdown. For multi option combinations (ie colour and size) this would need to be dynamic so if green selected then only sizes in stock that are green are shown.  If colour changed to Red then which sizes are shown should be updated.

The stock warning functionality should use stock levels for all option combinations and display out of stock items at that level rather than at the top product level.

**Comment by abrookbanks** [comment]
It's very easy at all especially when there are a few options (size/colour/fit). I believe there should be two checks;

1. Before any Selections: Check for any attributes that are out of stock for all combinations and grey the option out. e.g. Red is not available in any combo. 
2. Once all have been selected an AJAX call needs to then make a stock check on the chosen combination. e.g. Green may be available in some combinations.

**Comment by abrookbanks** [comment]
Actually there is a 3rd option;
3. Update the dropdowns as items are selected. This would be ideal but pretty heavy!

**Comment by havenswift-hosting** [comment]
Third option is by far the best and dont see that it would be that heavy especially if indexing is correct

**Comment by abrookbanks** [comment]
Be my guest LOL

**Comment by abrookbanks** [comment]
.. working backwards from the ```CubeCart_option_matrix``` table is literally impossible. Sadly this can only work once all options have been chosen.

**Comment by briansandall** [comment]
What if the first entry (or an admin-designated one) for each option were automatically selected as the 'default', and the non-value entries (e.g.  -- Please Select --) removed? Then the default values could be used to retrieve the initial matrix options, and every selection after that would have to correspond to a matrix entry.

Selecting a combination that is out-of-stock (meaning it has both use_stock set and stock_level of 0) would replace the 'Add-to-Cart' button with the out of stock message, and vice-versa. It'd be important to make sure stock level validation on the server follows the same logic when adding the product to the cart as it does when displaying the button or not.

**Comment by abrookbanks** [comment]
I like that @briansandall and it would certainly work! Thanks for sharing.

**Comment by briansandall** [comment]
@abrookbanks How would you like to handle non-required options that are part of the matrix?

There isn't an "option a: 1, option b: none" entry combination in the matrix, so either we need that type of entry or restrict the matrix to required options only.

Personally, I'd vote for both: all options should be required, and any option that is truly optional should have a 'None', 'N/A', un-checked, etc. option added to its potential values by store owners, with corresponding entries in the matrix.

Btw, I see this was opened in January - have you guys made any progress on it? I've [started](https://github.com/briansandall/v6/commits/issue814) working on it for my own store, but it would be nice not to reinvent the wheel if there is already a starting point somewhere. Cheers.

**Comment by bhsmither** [comment]
I've got 90% of my hack finished. Needs more testing.
http://cc605.smitherconsulting.com/test-bundle-1.html

**Comment by briansandall** [comment]
@bhsmither Nice! Do you happen to have a github branch available for it?

I noticed that your test site doesn't seem to update any other information, though; for example,the actual stock level (rather than the range), weight, product code, and potentially other information in the 'specification' tab, or disabling / re-enabling the 'Add to Basket' button based on the current stock / store settings.

The branch I linked above addresses the product specifications (including current stock level), though it doesn't yet have a nice display of in/out of stock like yours does. I plan on working on the 'Add to Basket' bit soon, as I feel that is a very important aspect of this issue.

**Comment by bhsmither** [comment]
It's a plugin and skin code edits. I just needed an "Instant Stock Check" - no frills.

**Comment by abrookbanks** [comment]
That's superb Brian! I know you are not a fan of PayPal. Will that stop you adding it to the extension marketplace?

**Comment by bhsmither** [comment]
Yes, it will.

But I am comfortable with posting my stuff in the CubeCartForums.org site, where projects can have their own discussion thread.

**Comment by abrookbanks** [comment]
It will get far more exposure on the official marketplace but it's up to you.

**Comment by briansandall** [comment]
@abrookbanks This seemed like something that you were considering adding to the core code base - would you prefer I make mine into a plugin instead?

Btw, are there code style guidelines that we should follow when contributing? There doesn't seem to be any standard based on the various files I've viewed so far - some use tabs, others varying numbers of spaces (2, 3, or 4). There's a [pretty nifty] (http://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs) way with git to use whatever you're comfortable with but still commit using the project-preferred indentation style.

@bhsmither Collaboration is the whole point of using Github, right? Forks are cheap, branches are cheap - it makes it so easy to contribute :)

**Comment by abrookbanks** [comment]
I'd love to see it in core. That's up to Brian though. :') Agree about forks etc.. LOVE GitHub. :+1:

**Comment by briansandall** [comment]
@abrookbanks I take it you're not interested in my fork, then? Here are screenshots of the stock levels / button updating:

In stock:
![cc_814-1](https://cloud.githubusercontent.com/assets/14335170/11003158/b94058be-8465-11e5-8db8-5ce5151b4151.png)

Out of stock:
![cc_814-0](https://cloud.githubusercontent.com/assets/14335170/11003141/aab4e332-8465-11e5-8434-217dae952a39.png)

It ended up that I didn't need to set the first choice as a default selection - it works fine with the current form handling.

**Comment by abrookbanks** [comment]
Definitely interested. I haven't had a chance to look yet. Thanks for all your efforts. 

I had a babymoon with my wife to Thailand and have been catching up ever since I got back. I haven't been able to look at GitHub issues over the last few weeks. Next week I should be able to put aside at least three solid days for it. I have to put tech support first as this keeps a roof on my head (and a beer in my neck).

**Comment by briansandall** [comment]
Lol, nice. Congrats, and looking forward to your return.

**Comment by abrookbanks** [comment]
I'm back already. Come Jan 16th (or there abouts) I'll be shoulders deep in sh!tty nappies I expect.

**Comment by briansandall** [comment]
I meant 'return' as in 'return to working on issues' - better get everything done before Jan 16th, you won't have any time, then!

**Comment by abrookbanks** [comment]
Trust me I was on work issues when I was in Thailand!! Hehehe. Only a couple of hours a day though. :)

**Comment by briansandall** [comment]
The proposed solution I have for issue #814 would also resolve this, as it dynamically updates the stock level based on the matrix options; the 'enhanced' version also updates the display of the 'Add to Cart' button and 'out of stock' message.

**Comment by briansandall** [comment]
As for hiding out-of-stock / disabled options, [this page](http://www.brownduck.com/store/p/112-Flame-Resistant-Canvas-Cargo-Pant.aspx) shows an interesting way to do it:

- Enable only the first select menu
- Once a selection is made, populate the next select menu with available options based on the first selection and enable it
- Once the 2nd selection is made, do so again for the next option, and so on
- Unselecting a previous option resets any that depend on it

What do you all think of this approach?

I think there should still be the option for store owners to disable it, so if they want all the options to appear right away they still can, but from the customer's perspective this would sure beat trying over and over to figure out a valid combination (if there were lots of options and groups, many of which were sold out or otherwise unavailable).

It would of course only work if the product was using the option matrix and if the matrix had the ability to enable / disable individual entries (see [examle](https://github.com/briansandall/v6/commit/b33bbca1ee0be06d5ae4b5e9b7cb9c22f42a269a) - pardon the mess), and we would have to figure out an efficient way to determine the available options, but it's totally doable.

Since the client should already have the full option arrays built, we could just send an array of option IDs to enable or disable (whichever is fewer, probably disable) plus the id of the option group to manipulate; since it would theoretically only be for one option group at a time, each response should be fairly light-weight.
