### ISSUE TITLE
Sitemap submission needs a control and should be OFF by default!

### ISSUE THREAD

**Issue by RedKiteDesigns** [cubecart/v6#761]
It is potentially bad to have google crawling your site and announcing it to the world while you are still developing it.

It might also be a goog idea to allow the user to specify other search engines to ping or otherwise inform of updated sitemaps.

I now have google listings for my site at the temporary access address http://nn.nn.nn.nn/~username/ and it's just full of test products and categories - bad for my business image.

You can turn it off by commenting out the following lines in seo.class.php at Line 719

			$request = new Request('www.google.com', '/webmasters/sitemaps/ping');
			$request->setMethod('get');
			$request->setData(array('sitemap' => $store_url.'/'.basename($filename)));
			$request->send();
			return true;

**Comment by havenswift-hosting** [comment]
If you are developing a site then it should always be in maintenance mode and then there is nothing to crawl.  You can also add robots.txt entries to re-enforce that the site should not be crawled although not strictly needed.

Whether you have a sitemap or not, it is likely that Google and Bing would eventually find your site and crawl it hence putting the store into maintenance mode.  A well constructed sitemap helps the search engines find the site and site structure quicker and often enables them to index more pages at a quicker rate.

Once the store is live you should submit your sitemaps via the webmaster tools for the various search engines rather than rely on the ping anyway although having a few extra sitemaps that are pinged would be a good idea.

The built in sitemap is better than nothing but has to be manually generated (ie cannot be done on a regular schedule via cron as many can be) and also only does CubeCart pages.  We always recommend using a specialist sitemap software to create standard xml plus also image, video, news sitemaps where appropriate.

This is not a bug / problem with CubeCart but rather in the usage whilst building a site

**Comment by bhsmither** [comment]
I like all your points:
A series of checkboxes to select to 'ping' the various search engines
A notice on the Rebuild-a-SiteMap checkbox that a ping will automatically take place
Suppressing all pings when the site is in Offline mode

When evaluating CubeCart, one may haphazardly check boxes, click links, and do any manner of things to see if the application meets your needs - knowing full well that such actions are completely devoid of knowing what the consequences may be. Generally, no harm is done as one can obliterate the installation and database and start over. However, there may be consequences when CubeCart reaches out beyond its environment. (Includes getting outside data such as the Google Taxonomy list.)

Suggest, after installation, the final step is to have the store in offline mode and the default admin logged in so that the admin can view the store offline. While offline, no contact is made outside the environs of the installation.

**Comment by abrookbanks** [comment]
I tweaked the code to prevent it pinging Google if the store is offline. Thats a good start!

**Comment by RedKiteDesigns** [comment]
Cheers Al,

 

A good start indeed. Probably enough – how about having the store off by default (I think it is) and display a warning message when you turn it on for the 1st time.

 

It’s not necessarily something you think of when you’re trying out a cms or e-commerce framework.

 

Clive

**Comment by abrookbanks** [comment]
Yeah I totally agree.
