### ISSUE TITLE
Security Alert: Possible Cross-Site Request Forgery (CSRF)

### ISSUE THREAD

**Issue by pbullert** [cubecart/v6#799]
"Security Alert: Possible Cross-Site Request Forgery (CSRF) or browser back button used."

This error pops up frequently preventing me to login to the dashboard, happens especially on chrome browser and localhost setups.

If there are workaround this? I have a few local stores which don't allow me to login.

![csrf](https://cloud.githubusercontent.com/assets/13545534/9750608/af2f5b4c-565f-11e5-8f09-6a58e63b1c41.jpg)

**Comment by abrookbanks** [comment]
I've seen this but second login attempt works fine in all Browsers. Are sessions working? Can you try adding items to the basket on the front end? If it holds basket data sessions are working. If not then sessions need sorting on the server.

**Comment by havenswift-hosting** [comment]
There was / is another git issue on this subject and also some threads on the forums so it affects a lot of people.

A second attempt will always work and allow you to login as we and many of our customers see this regularly, so while it is annoying and concerning for many, it isnt a major issue.

Sessions are working fine - this happens if the user agent (or IP address which can also happen with dynamic changes) changes in any way from the last time that admin user attempted to login. So any update (which Chrome does do quite often) will cause this, or logging in using a different browser (I regularly use Chrome and Firefox) on the same computer or using the same browser on an iPhone, iPad when usually using a PC etc etc

**Comment by pbullert** [comment]
On live sites, a refresh usually did it.

When i'm doing development on local setups, i am not able to get rid of the lockout on chrome especially. 
Adding items to basket does not work. Is there some kind of workaround for development environments?

I am not able to login to the dashboard of any of my local setups using chrome.

**Comment by briansandall** [comment]
This is a common issue, and seems to be due to both Chrome's strict cookie policies and CubeCart having some trouble with 'localhost'.

Changing your site URLs to 127.0.0.1 instead of localhost, as well as setting your cookie domain under 'Store Settings'->'SSL'  tab to 127.0.0.1 should allow you to log in with Chrome, as well as resolve other issues with checking out / viewing the cart.

See this thread for more information: https://forums.cubecart.com/topic/50319-resolved-issues-getting-started/?do=findComment&comment=212331

**Comment by havenswift-hosting** [comment]
This is not specifically a Chrome issue nor a localhost issue

**Comment by abrookbanks** [comment]
> not specifically a Chrome issue nor a localhost issue

Yes I think that is what's commonly known as a red herring. :-)

**Comment by briansandall** [comment]
Interesting, because no matter how many times I try to login using Chrome, it always gives me the same error message unless I switch to 127.0.0.1, so [quote]A second attempt will always work[/quote] didn't help me resolve the issue which, in my particular case, did seem to be specific to Chrome / localhost - IE and Firefox both worked flawlessly with the initial settings.

**Comment by digioz** [comment]
I had the same problem and using 127.0.0.1 did solve the issue (or at least work around it). It essentially appears that "localhost" is not supported by the system.
