### ISSUE TITLE
Product specifications not affected by selected options

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#814]
When viewing a product with options, none of the specifications update based on the selected options, showing only the base product's values.

For example, Product A comes in 3 Sizes (S, M, L) each with a unique product code (A-{size}), and each size above S adds 0.2 lbs to the weight. When viewing the specs, one always sees:
    Product Code  A-X  // 'X' being the placeholder used in the base product
    Weight            1.000Lb

Viewing a size M (for example), however, should display:
    Product Code  A-M
    Weight            1.200Lb

**Comment by briansandall** [comment]
I've never worked with Smarty before, but looking in content.product.php, I can see the price seems to be affected by the presences of 'data-price' tags throughout the template, for which I can only assume there is some JS or AJAX being automatically called to update the values on the page.

Could the same thing be done for product codes and weight, e.g. add
'data-weight="{$option.values.0.decimal_weight}"' to the various option input tags alongside that for price, as well as something like:
<td 'data-weight="{$PRODUCT.product_weight}">{$PRODUCT.product_weight}</td>

I'll play around with it some tomorrow and see what I can do, but it still seems a lot like magic to me.

**Comment by briansandall** [comment]
Alright, finally had some time to play with it: https://github.com/briansandall/v6/commit/c3ac85c0951a7f1fe232636c2d645a5322feef67

I wrote it so that it only performs an Ajax call if every option choice has been made, and it resets to the original product values if a choice is unmade.

I didn't see anywhere on the content.product.php page that the product ID is available to JavaScript; if it was and was sent with the Ajax request along with whatever product options were available, it could be written to be even more dynamic, updating weights and such based on partial selections.

What do you think? Any suggestions to improve it?

**Comment by briansandall** [comment]
This also addresses [this](https://forums.cubecart.com/topic/50429-options-matrix-product-page-stock-levels/#comment-212889) topic - it shows exact stock levels for the selected options, rather than a range.

**Comment by briansandall** [comment]
If we added a `matrix_id` column to cubecart_image_index using my 814 branch as the basis, it should be possible to have one (or more!) images specific to a matrix entry, so as the user selects options, the product images would dynamically update to reflect their choices.

I'm going to give it a go and see how it turns out.

**Comment by havenswift-hosting** [comment]
I cant see that you would ever need a different image at a matrix level - what combination of options would ever need a different image ?  For example a clothes shop having a matrix of colour and sizes, having different images for each colour is enough but having one for each matrix item makes little sense.  We already have a plugin where it is possible to allocate a different image to one set of options within a matrix set and the image is dynamically changed - you can see it in operation with our Nautical and Retail Therapy skins (our newest Party Time and the stock Foundation skins dont have this installed) on our demo site https://www.cubecart-demo.co.uk

**Comment by briansandall** [comment]
@havenswift-hosting You're right, I meant at an option level, but I was stuck thinking about the matrix. Your test site looks quite nice, btw, and yes, that's exactly the type of functionality I was hoping to achieve.

Can your plugin handle multiple images per option entry, e.g. both a front and a back image of each color?

Is your plugin freely available? I'm hoping this type of functionality makes its way into the core code.

**Comment by havenswift-hosting** [comment]
OK I understand that it can be easy to mix up !  Thanks for the compliments on that skin, there are another couple there as well as the default one and the other two display the standard homepage document which details various plugins. That plugin isnt freely available purely because of the amount / cost of the time put into developing it and also the commitment to support it going forward.

That plugin doesnt support multiple images but we do have another one on that same site that does and if you look at a category page or the latest products and hover the mouse over an image, it changes to an alternate.  So these two plugins together work extremely well together and give exactly the functionality I think you are looking for.

The idea with CubeCart is to have a strong but lean core product that provides the basics for most users and then plugins can be added for functionality that certain users want.  I think this is a much better approach than having a massively bloated product that still doesnt cover all functionality - see Magento which while it is a good product, is HUGE and still has a massive number of extensions

**Comment by briansandall** [comment]
Sure, can't please everybody ;)

However, I hope you and others take a look at my [proposed changes](https://github.com/briansandall/v6/tree/issue814_fixed) for the original issue I brought up, i.e. the product specifications do not update based on the currently selected options.

I think if you checkout the branch on a local CubeCart install and give it a whirl, all of the changes should be pretty universally applicable without (hopefully) detracting from anyone's previous efforts at developing plugins.

I'm pretty new to the CC scene, though, and haven't spent much time looking at plugins, so I don't really know what's available or if there are 'protected' features that shouldn't be given away freely. I just figured if the cart is free and open source, anything I develop for it may as well be, too; I can keep them private / release them as my own plugins if that would be preferable - I certainly wouldn't mind making money ;)

**Comment by havenswift-hosting** [comment]
Personally I think that it is fantastic that CubeCart went open source and that we have a few good new developers coming along that really embrace that and want to contribute to core and github is great for that - the success of WordPress in particular but other Open Source projects is based entirely on this principle. Al is currently the only one that makes a decision whether anything gets into core though !

There is always a debate to be had about whether functionality should go into core or not.  I personally believe it should kept lean although I agree that the way that product options function in CubeCart is great (and better than most other packages) it does still need some improvements especially when working with options matrix and that should be in core.

Again in my view, anything else should be in the form of plugins which can either be made freely available or on a commercial basis - ideally via the Extensions marketplace (although I am still guilty of not adding many of our plugins there purely from a lack of time !).  Commercial plugins do help some developers earn revenue and stay around CubeCart and likewise having a small optional annual support / maintenance fee allows those developers to commit to supporting and developing those plugins / skins into the future.  The history of CubeCart and other applications is littered with the  disappearance of great developers because they couldnt carry on supporting products for free they had committed to and werent getting any further revenue. Another point is that since CubeCart went Open Source, support contracts and the extensions marketplace are pretty much the only source of revenue for Al who has put years and years of time and effort into developing CubeCart !

Our main business is providing quality hosting for CubeCart websites and skins / plugins are a means to an end and while we do offer many of these on a commercial basis, we have also created some free ones and also fed some code changes back into core (another one for the free AusPost plugin will be made later today) so to my mind having a vibrant community is what is most important to the future development and expansion of CubeCart.

Not sure how this advances this "issue" and maybe this wasnt the correct place for this posting but there you go !

**Comment by briansandall** [comment]
Thanks for the response! I've sort of mentioned this to Al, but now that CubeCart is open source, it wouldn't be a bad idea to have contributor guidelines, similar to the information you provided above, somewhere highly visible to potential contributors, e.g. the readme.

**Comment by briansandall** [comment]
Re: dynamic images - I do see, however, that the 'CubeCart_option_matrix' table has an 'image' column... perhaps it was planned at one point to allow matrix entries to specify an image?

It would be useful for products with multiple options where the combination had a unique image, e.g. t-shirt color + neck style; images switching based on a single option would be insufficient in such a case, though it seems it was only planned to allow one image per entry. Hmm...

**Comment by havenswift-hosting** [comment]
Yes there is only one image column so wouldnt by itself cater for your needs even if it was used.  I also still dont see that your example in real life two t-shirts with different neck styles would be different products with different SKU / bar codes

**Comment by briansandall** [comment]
As would t-shirts of different colors - thus the 'product_code' column in the matrix table.

In the end, it's simply about presentation - different items are grouped together with 'options' to make the experience easier on the customer.

Anyway, I was just pointing out the table layout, not trying to start an argument. I don't have a need for multiple images per matrix entry at this point in time; if I do at a later date, I have some ideas of how to go about implementing it that should suffice.

We probably should have started a separate issue for all this discussion on images...

**Comment by briansandall** [comment]
Alright, here we go - I finally cleaned this up and rebased it on top of the current master branch.

Keep in mind that the goal is for the product specifications to match what was entered in the options and option matrix, e.g. product code, weight, stock level, that kind of thing, so that the customer can see the actual specs of what they are purchasing as opposed to the generic ones for the product as a whole.

This is accomplished by piggybacking a few extra bits of data onto the already-occurring AJAX request that occurs each time an option is changed, resulting in an improved user experience for negligible if any difference in performance and without any changes to the admin panel, i.e. store owners won't need to do change a thing.

@abrookbanks Please let me know which, if any, of the following you would like a PR for. Of course, I recommend number 3, which includes everything ;)

1. [Base feature](https://github.com/briansandall/v6/commits/issue814)

2. [Enhanced](https://github.com/briansandall/v6/commits/issue814_expanded) - These additional commits allow the product page to dynamically refresh such that the 'Add to Cart' button and 'Out of Stock' message match the currently selected option matrix, if any. I think this is a really nice enhancement with very minimal changes and no performance difference, as customers get immediate feedback on whether their current selection is available for purchase.

3. [Optional](https://github.com/briansandall/v6/commits/issue814_optional) - Adds a store configuration option to allow products and their matrix option entries to use independent stock settings, allowing for scenarios such as tracking stock for a product in general but allowing a certain combination to ignore stock and always be available (perhaps you can acquire more of that particular combo very easily). It's only 1 commit, so it could just as easily be applied only to the base feature as to the enhanced version. Note that the implementation of the base feature allows independent stock settings by default, whereas with this option it becomes disabled by default (meaning the parent product's 'use_stock' value is used, restoring what seems to be the original behavior).
