### ISSUE TITLE
Condition to unset record fails for 'product_weight'

### ISSUE THREAD

**Issue by briansandall** [cubecart/v6#827]
In /admin/sources/products.index.inc.php on [line 68](https://github.com/cubecart/v6/blob/master/admin/sources/products.index.inc.php#L68):

``` php
if (empty($record[$r]) && $record[$r]!=='0' && $record[$r]!=='0.0') {
```

Product weight is of type DECIMAL(10,3) in the cubecart_inventory table, meaning that it will always be in the format '0.000' when pulled from the database with a zero value - as such, it will not match the above conditionals. It should probably use a regex such as:

``` php
if (empty($record[$r]) && preg_match('/^(0|0\.0+)$/', $record[$r])) {
    unset($record[$r]);
}
```

There is a comment in the code explaining that the above is designed to prevent certain SQL errors - which ones would those be? 'stock_level' and 'stock_warning' both have a default of zero, and 'product_weight', while it defaults to null, should not have any issue being set to zero. Anyway, just curious.

**Comment by abrookbanks** [comment]
Thanks thats a nice tweak. I'm not sure what the SQL error would be.

**Comment by bhsmither** [comment]
And I thought
```
if (empty($record[$r]) && !is_numeric($record[$r])) {
```
was good enough.

`$record` is from `$_POST`, not a database query result. However, still considered a string. Apparently we are looking to unset any empty value _except_ the (PHP empty) strings '0' and '0.0'. But if we also want to _exempt_ from unsetting *any* string that looks like it is zero, including **00.00**, etc, then the statement should be `!preg_match` with any number of zeroes with maybe a following period with maybe a following any number of zeroes.

Which is why I chose `!is_numeric()`. (I thought I brought this up circa CC5210, but can't find it. Probably a support ticket.)

**Comment by briansandall** [comment]
@bhsmither Don't know how I missed that $record is just the $_POST array... that's embarrassing :P. You're right, then, that the original code is probably fine, or we can modify it to account for any number of leading or trailing zeroes:
```php
preg_match('/^(0+|0+\.0+)$/', $record[$r])
```

**Comment by abrookbanks** [comment]
I missed it too.

**Comment by bhsmither** [comment]
I believe the concerns over SQL errors were appropriate in early versions of CC5 before CubeCart code was added to force the MySQL Mode to **not** be 'strict'.

In strict mode, MySQL is not allowed to second-guess what you meant when you attempted to insert an otherwise illegal value into a column: a null or any kind of string into an INTEGER column, for example.

**Comment by briansandall** [comment]
That makes sense - so is this section of code completely redundant now?

I ask also because I'm hoping to turn [this](https://github.com/briansandall/v6/commit/e7c1d82c73e1e84594c36dee2f5f9f490c0422d5) into a PR, and if this check is still needed I will need to add the new fields to the $records array.

**Comment by abrookbanks** [comment]
Thanks guys, from my testing !is_numeric works well. It may be redundant but maybe best to leave in just in case. Sorry if I have missed anything in the past Brian. Moving to GitHub has helped massively so hopefully things don't get missed anymore.
