### ISSUE TITLE
Email Templates in Database Need Updating

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#884]
The fix for #604 has a problem. Earlier, #587 and #596 made changes to the databased templates.

However, changes were made to only the `content_html` column. No change was made to the `content_text` column, which will probably cause the database server some grief.

I believe the statement that removes the `replace` modifier that used apostrophes was meant for the `content_text` column.

**Comment by abrookbanks** [comment]
This issue was that the rich text editor screwed up the smarty tags by HTML encoding them and thus causing a fatal error trying to send parse the email content. Getting CKEditor to play nice with smarty has been a total impossibility. Only the content_html data is parsed within CKEditor and as a result the content_text column doesn't need amending. 

On save;

```{$DATA.ship_method|replace:'_':' '}```

changes to;

```{$DATA.ship_method|replace:&#39;_&#39;:&#39; &#39;}```

No changes necessary.
