### ISSUE TITLE
Upgrade SQL Syntax

### ISSUE THREAD

**Issue by bhsmither** [cubecart/v6#912]
In 5.0.0b1.sql, line 276, please verify that:
```
UPDATE `CubeCart_filemanager` SET `filepath` = REPLACE(`filepath`, 'images\uploads\\', ''); #EOQ
```
is syntactically correct with respect to the backslashes.

**Comment by briansandall** [comment]
Looks fine to me: according to the [manual](https://dev.mysql.com/doc/refman/5.7/en/string-literals.html), it doesn't appear that \u has any special meaning, but the final \ needs to be escaped otherwise it will be interpreted as escaping the closing quotation mark.

Of course, the first \ could also be escaped, and probably should be both so its meaning is more semantically evident and to preclude any future errors should \u suddenly be giving special meaning.

**Comment by abrookbanks** [comment]
Thanks Brian.
