### ISSUE TITLE
Defer parsing of skin javascript

### ISSUE THREAD

**Issue by havenswift-hosting** [cubecart/v6#967]
The Foundation skin (and all skins based on it) uses some sizeable JavaScript files and these are all parsed during initial page load. If possible you should defer parsing of JavaScript to reduce blocking of page rendering.  This will greatly increase page load speeds.

**Comment by abrookbanks** [comment]
Most JS is rendreed just before the closing body tab. All other need to be in the head tag. 

The JS can be compressed along with CSS but it is intentionally not so that its easy for people to modify. Foundation is a starting block for custom skin. A lot of our users wouldn't understand a compressed CSS/JS file.

**Comment by havenswift-hosting** [comment]
Try putting a standard Foundation skin based CubeCart site through a gtmetrix.com test and you will see what is flagged.  I understand some is before the end body but there are techniques to defer the rest

Compression is a different point and I would argue that anyone who would consider changing core css (shouldn't be any need anyway) would also understand how to decompress.
